import type { ComponentDefinition } from '../component/definition';
import { ComponentRegistry } from './component-registry';

const columnChildren = [
    'layout.container',
    'layout.stack',
    'layout.flex',
    'layout.grid',
    'layout.columns',
    'layout.spacer',
    'layout.divider',
    'content.heading',
    'content.text',
    'content.richtext',
    'content.button',
    'content.link',
    'media.image',
    'marketing.card',
    'reusable.instance',
] as const;

const internalLayoutChildren = [...columnChildren] as const;

export const BUILT_IN_COMPONENT_DEFINITIONS: ComponentDefinition[] = [
    {
        type: 'layout.root',
        name: 'Root',
        category: 'layout',
        description: 'Structural document root for rendering top-level page sections.',
        capabilities: {
            canHaveChildren: true,
            canAcceptChildren: true,
            supportsResponsiveStyles: false,
        },
        defaultProps: {},
        defaultStyles: {},
        styleCapabilities: [],
        propSchema: {},
        childRules: {
            allowedTypes: ['layout.section'],
        },
        integration: {
            rendererKey: 'layout.root',
        },
    },
    {
        type: 'layout.section',
        name: 'Section',
        category: 'layout',
        description: 'Top-level page section for grouping layout and content nodes.',
        capabilities: {
            canHaveChildren: true,
            canAcceptChildren: true,
            supportsResponsiveStyles: true,
        },
        defaultProps: {},
        defaultStyles: {
            desktop: {
                display: 'block',
                width: '100%',
                position: 'relative',
                margin: '0 auto',
                padding: '10px',
                backgroundColor: 'white',
                color: 'black',
                paddingTop: { value: 10, unit: 'px' },
                paddingBottom: { value: 10, unit: 'px' },
                paddingLeft: { value: 0, unit: 'px' },
                paddingRight: { value: 0, unit: 'px' },
            },
        },
        styleCapabilities: [
            'display',
            'width',
            'minHeight',
            'margin',
            'padding',
            'paddingTop',
            'paddingRight',
            'paddingBottom',
            'paddingLeft',
            'backgroundColor',
            'position',
            'overflow',
            'borderWidth',
            'borderStyle',
            'borderColor',
            'borderRadius',
            'boxShadow',
            'opacity',
        ],
        propSchema: {},
        childRules: {
            allowedTypes: ['layout.row', 'layout.container'],
        },
        integration: {
            rendererKey: 'layout.section',
            editorKey: 'layout.section',
        },
    },
    {
        type: 'layout.row',
        name: 'Row',
        category: 'layout',
        description: 'Horizontal composition layer inside a Section.',
        capabilities: {
            canHaveChildren: true,
            canAcceptChildren: true,
            supportsResponsiveStyles: true,
        },
        defaultProps: {},
        defaultStyles: {
            desktop: {
                display: 'flex',
                flexDirection: 'row',
                width: '100%',
                maxWidth: '900px',
                margin: '0 auto',
                padding: '10px',
                backgroundColor: 'transparent',
                gap: '1rem',
                flexWrap: 'nowrap',
            },
        },
        styleCapabilities: [
            'display',
            'width',
            'minHeight',
            'maxWidth',
            'margin',
            'padding',
            'gap',
            'flexDirection',
            'justifyContent',
            'alignItems',
            'flexWrap',
            'overflow',
            'position',
            'borderWidth',
            'borderStyle',
            'borderColor',
            'borderRadius',
            'boxShadow',
            'opacity',
            'backgroundColor',
        ],
        propSchema: {},
        childRules: {
            allowedTypes: ['layout.column'],
        },
        integration: {
            rendererKey: 'layout.row',
            editorKey: 'layout.row',
        },
    },
    {
        type: 'layout.column',
        name: 'Column',
        category: 'layout',
        description: 'Content container inside a Row.',
        capabilities: {
            canHaveChildren: true,
            canAcceptChildren: true,
            supportsResponsiveStyles: true,
        },
        defaultProps: {},
        defaultStyles: {
            desktop: {
                display: 'flex',
                flexDirection: 'column',
                gap: '1rem',
                width: '100%',
                maxWidth: '900px',
                margin: '0 auto',
                padding: '10px',
                backgroundColor: 'transparent',
            },
        },
        styleCapabilities: [
            'display',
            'width',
            'minWidth',
            'maxWidth',
            'minHeight',
            'margin',
            'padding',
            'gap',
            'flexDirection',
            'justifyContent',
            'alignItems',
            'flexWrap',
            'overflow',
            'position',
            'borderWidth',
            'borderStyle',
            'borderColor',
            'borderRadius',
            'boxShadow',
            'opacity',
            'backgroundColor',
        ],
        propSchema: {},
        childRules: {
            allowedTypes: [...columnChildren],
        },
        integration: {
            rendererKey: 'layout.column',
            editorKey: 'layout.column',
        },
    },
    {
        type: 'layout.container',
        name: 'Container',
        category: 'layout',
        description: 'Nested layout primitive for constraining and grouping child components.',
        capabilities: {
            canHaveChildren: true,
            canAcceptChildren: true,
            supportsResponsiveStyles: true,
        },
        defaultProps: {},
        defaultStyles: {
            desktop: {
                maxWidth: '900px',
                width: '100%',
                display: 'block',
                margin: '0 auto',
                padding: '10px',
                backgroundColor: 'transparent',
            },
        },
        styleCapabilities: [
            'display',
            'width',
            'maxWidth',
            'margin',
            'padding',
            'gap',
            'flexDirection',
            'justifyContent',
            'alignItems',
            'backgroundColor',
        ],
        propSchema: {},
        childRules: {
            allowedTypes: [...internalLayoutChildren],
        },
        integration: {
            rendererKey: 'layout.container',
            editorKey: 'layout.container',
        },
    },
    {
        type: 'layout.stack',
        name: 'Stack',
        category: 'layout',
        description: 'A vertical flow layout with consistent spacing.',
        capabilities: { canHaveChildren: true, canAcceptChildren: true, supportsResponsiveStyles: true },
        defaultStyles: { desktop: { display: 'flex', flexDirection: 'column', gap: '1rem' } },
        styleCapabilities: [
            'display',
            'width',
            'minHeight',
            'maxWidth',
            'margin',
            'padding',
            'gap',
            'flexDirection',
            'justifyContent',
            'alignItems',
            'flexWrap',
            'backgroundColor',
        ],
        propSchema: {},
        childRules: { allowedTypes: [...internalLayoutChildren] },
        integration: { rendererKey: 'layout.stack', icon: 'stack' },
    },
    {
        type: 'layout.flex',
        name: 'Flex',
        category: 'layout',
        description: 'A flexible row or column layout primitive.',
        capabilities: { canHaveChildren: true, canAcceptChildren: true, supportsResponsiveStyles: true },
        defaultStyles: { desktop: { display: 'flex', flexDirection: 'row', gap: '1rem' } },
        styleCapabilities: [
            'display',
            'width',
            'minHeight',
            'maxWidth',
            'margin',
            'padding',
            'gap',
            'flexDirection',
            'justifyContent',
            'alignItems',
            'flexWrap',
            'backgroundColor',
        ],
        propSchema: {},
        childRules: { allowedTypes: [...internalLayoutChildren] },
        integration: { rendererKey: 'layout.flex', icon: 'flex' },
    },
    {
        type: 'layout.grid',
        name: 'Grid',
        category: 'layout',
        description: 'A responsive grid for cards and repeated content.',
        capabilities: { canHaveChildren: true, canAcceptChildren: true, supportsResponsiveStyles: true },
        defaultStyles: { desktop: { display: 'grid', gridTemplateColumns: 'repeat(3, minmax(0, 1fr))', gap: '1rem' } },
        styleCapabilities: ['display', 'width', 'minHeight', 'maxWidth', 'margin', 'padding', 'gap', 'gridTemplateColumns', 'backgroundColor'],
        propSchema: {},
        childRules: { allowedTypes: [...internalLayoutChildren] },
        integration: { rendererKey: 'layout.grid', icon: 'grid' },
    },
    {
        type: 'layout.columns',
        name: 'Columns',
        category: 'layout',
        description: 'A simple multi-column composition primitive.',
        capabilities: { canHaveChildren: true, canAcceptChildren: true, supportsResponsiveStyles: true },
        defaultStyles: { desktop: { display: 'flex', flexDirection: 'row', gap: '1rem' } },
        styleCapabilities: [
            'display',
            'width',
            'minHeight',
            'maxWidth',
            'margin',
            'padding',
            'gap',
            'flexDirection',
            'justifyContent',
            'alignItems',
            'flexWrap',
        ],
        propSchema: {},
        childRules: { allowedTypes: [...internalLayoutChildren] },
        integration: { rendererKey: 'layout.columns', icon: 'columns' },
    },
    {
        type: 'layout.spacer',
        name: 'Spacer',
        category: 'layout',
        description: 'Adds intentional vertical space to a composition.',
        capabilities: { supportsResponsiveStyles: true },
        defaultStyles: { desktop: { minHeight: '2rem' } },
        styleCapabilities: ['width', 'height', 'minHeight', 'maxHeight', 'margin'],
        propSchema: {},
        childRules: { allowedTypes: [] },
        integration: { rendererKey: 'layout.spacer', icon: 'spacer' },
    },
    {
        type: 'layout.divider',
        name: 'Divider',
        category: 'layout',
        description: 'A visual separator between content groups.',
        capabilities: { supportsResponsiveStyles: true },
        defaultStyles: { desktop: { borderWidth: '1px', borderStyle: 'solid', borderColor: 'hsl(160 10% 88%)' } },
        styleCapabilities: ['width', 'margin', 'borderWidth', 'borderStyle', 'borderColor'],
        propSchema: {},
        childRules: { allowedTypes: [] },
        integration: { rendererKey: 'layout.divider', icon: 'divider' },
    },
    {
        type: 'content.heading',
        name: 'Heading',
        category: 'content',
        description: 'Text heading content primitive.',
        capabilities: {
            supportsText: true,
            supportsResponsiveStyles: true,
        },
        defaultProps: {
            text: 'Heading',
            level: 2,
        },
        defaultStyles: {
            desktop: {
                fontSize: '2rem',
                color: 'black',
            },
        },
        styleCapabilities: ['margin', 'padding', 'color', 'fontFamily', 'fontSize', 'fontWeight', 'lineHeight', 'textAlign'],
        propSchema: {
            text: { type: 'string' },
            level: { type: 'integer', min: 1, max: 6 },
        },
        childRules: {
            allowedTypes: [],
        },
        integration: {
            rendererKey: 'content.heading',
            editorKey: 'content.heading',
        },
    },
    {
        type: 'content.text',
        name: 'Text',
        category: 'content',
        description: 'A readable paragraph of body copy.',
        capabilities: { supportsText: true, supportsResponsiveStyles: true },
        defaultProps: { text: 'Add a paragraph of text.' },
        defaultStyles: { desktop: { fontSize: '1rem', lineHeight: 1.6, color: 'black' } },
        styleCapabilities: [
            'margin',
            'padding',
            'color',
            'fontFamily',
            'fontSize',
            'fontWeight',
            'lineHeight',
            'letterSpacing',
            'textTransform',
            'textDecoration',
            'textAlign',
        ],
        propSchema: { text: { type: 'string' } },
        childRules: { allowedTypes: [] },
        integration: { rendererKey: 'content.text', icon: 'text' },
    },
    {
        type: 'content.richtext',
        name: 'Rich Text',
        category: 'content',
        description: 'Structured editorial copy for longer content.',
        capabilities: { supportsText: true, supportsResponsiveStyles: true },
        defaultProps: { text: 'Add rich text content.' },
        defaultStyles: { desktop: { color: 'black' } },
        styleCapabilities: [
            'margin',
            'padding',
            'color',
            'fontFamily',
            'fontSize',
            'fontWeight',
            'lineHeight',
            'letterSpacing',
            'textTransform',
            'textDecoration',
            'textAlign',
        ],
        propSchema: { text: { type: 'string' } },
        childRules: { allowedTypes: [] },
        integration: { rendererKey: 'content.richtext', icon: 'rich-text' },
    },
    {
        type: 'content.button',
        name: 'Button',
        category: 'content',
        description: 'A clear action link for visitors.',
        capabilities: { supportsText: true, supportsResponsiveStyles: true },
        defaultProps: { text: 'Get started', href: '#' },
        defaultStyles: {
            desktop: {
                display: 'inline-block',
                padding: '0.75rem 1rem',
                backgroundColor: 'hsl(158 64% 32%)',
                color: 'white',
                borderRadius: '0.5rem',
                textAlign: 'center',
            },
        },
        styleCapabilities: [
            'display',
            'margin',
            'padding',
            'color',
            'backgroundColor',
            'fontFamily',
            'fontSize',
            'fontWeight',
            'lineHeight',
            'textAlign',
            'borderRadius',
            'borderWidth',
            'borderStyle',
            'borderColor',
            'boxShadow',
        ],
        propSchema: { text: { type: 'string' }, href: { type: 'string' } },
        childRules: { allowedTypes: [] },
        integration: { rendererKey: 'content.button', icon: 'button' },
    },
    {
        type: 'content.link',
        name: 'Link',
        category: 'content',
        description: 'A lightweight inline navigation link.',
        capabilities: { supportsText: true, supportsResponsiveStyles: true },
        defaultProps: { text: 'Learn more', href: '#' },
        styleCapabilities: ['margin', 'color', 'fontFamily', 'fontSize', 'fontWeight', 'lineHeight', 'textDecoration', 'textAlign'],
        propSchema: { text: { type: 'string' }, href: { type: 'string' } },
        childRules: { allowedTypes: [] },
        integration: { rendererKey: 'content.link', icon: 'link' },
    },
    {
        type: 'media.image',
        name: 'Image',
        category: 'media',
        description: 'An image reference with accessible alt text.',
        capabilities: { supportsResponsiveStyles: true },
        defaultProps: { src: '', alt: '' },
        styleCapabilities: ['display', 'width', 'height', 'minWidth', 'maxWidth', 'margin', 'borderRadius', 'objectFit'],
        propSchema: { src: { type: 'string' }, alt: { type: 'string' } },
        childRules: { allowedTypes: [] },
        integration: { rendererKey: 'media.image', icon: 'image' },
    },
    {
        type: 'marketing.card',
        name: 'Card',
        category: 'marketing',
        description: 'A contained surface for grouped content.',
        capabilities: { canHaveChildren: true, canAcceptChildren: true, supportsResponsiveStyles: true },
        defaultStyles: {
            desktop: {
                display: 'flex',
                flexDirection: 'column',
                gap: '0.75rem',
                padding: '1.5rem',
                backgroundColor: 'white',
                borderWidth: '1px',
                borderStyle: 'solid',
                borderColor: 'hsl(160 10% 88%)',
                borderRadius: '0.75rem',
                boxShadow: '0 1px 2px rgba(0,0,0,.08)',
            },
        },
        styleCapabilities: [
            'display',
            'width',
            'minHeight',
            'maxWidth',
            'margin',
            'padding',
            'gap',
            'flexDirection',
            'justifyContent',
            'alignItems',
            'backgroundColor',
            'borderWidth',
            'borderStyle',
            'borderColor',
            'borderRadius',
            'boxShadow',
        ],
        propSchema: {},
        childRules: { allowedTypes: [...internalLayoutChildren] },
        integration: { rendererKey: 'marketing.card', icon: 'card' },
    },
    {
        type: 'reusable.instance',
        name: 'Reusable component',
        category: 'content',
        description: 'A reference to an owned reusable component definition.',
        capabilities: { supportsResponsiveStyles: false },
        defaultProps: {},
        defaultStyles: {},
        styleCapabilities: [],
        propSchema: {},
        childRules: { allowedTypes: [] },
        integration: { rendererKey: 'reusable.instance' },
    },
];

export function createBuiltInComponentRegistry(): ComponentRegistry {
    return new ComponentRegistry(BUILT_IN_COMPONENT_DEFINITIONS);
}
