<?php

namespace App\Builder\Registry;

use App\Builder\Component\ComponentDefinition;

final class BuiltInComponentDefinitions
{
    /**
     * @return list<ComponentDefinition>
     */
    public static function all(): array
    {
        $columnChildren = [
            'layout.row', 'layout.container', 'layout.stack', 'layout.flex', 'layout.grid', 'layout.columns', 'layout.spacer', 'layout.divider', 'layout.navbar',
            'content.heading', 'content.text', 'content.richtext', 'content.button', 'content.link', 'content.list', 'content.accordion', 'content.tabs', 'media.image', 'media.gallery', 'media.carousel', 'embed.video', 'code.customcode', 'marketing.card', 'marketing.blurb', 'marketing.pricing', 'marketing.logomarquee', 'marketing.stats', 'marketing.testimonial', 'form.contact', 'marketing.imagefeature', 'reusable.instance',
            'marketing.countdown', 'content.socialicons', 'content.alert', 'marketing.progressbar',
        ];
        $internalLayoutChildren = $columnChildren;

        return [
            new ComponentDefinition(
                type: 'layout.root',
                name: 'Root',
                category: 'layout',
                description: 'Structural document root for rendering top-level page sections.',
                capabilities: [
                    'canHaveChildren' => true,
                    'canAcceptChildren' => true,
                    'supportsResponsiveStyles' => false,
                ],
                defaultProps: [],
                defaultStyles: [],
                styleCapabilities: [],
                propSchema: [],
                childRules: [
                    'allowedTypes' => ['layout.section', 'layout.navbar'],
                ],
                integration: [
                    'rendererKey' => 'layout.root',
                ],
            ),
            new ComponentDefinition(
                type: 'layout.section',
                name: 'Section',
                category: 'layout',
                description: 'Top-level page section for grouping layout and content nodes.',
                capabilities: [
                    'canHaveChildren' => true,
                    'canAcceptChildren' => true,
                    'supportsResponsiveStyles' => true,
                ],
                defaultProps: [],
                defaultStyles: [
                    'desktop' => [
                        'display' => 'block',
                        'width' => '100%',
                        'minHeight' => '50px',
                        'position' => 'relative',
                        'margin' => '0 auto',
                        'padding' => '10px',
                        'backgroundColor' => 'transparent',
                        'paddingTop' => ['value' => 10, 'unit' => 'px'],
                        'paddingBottom' => ['value' => 10, 'unit' => 'px'],
                        'paddingLeft' => ['value' => 0, 'unit' => 'px'],
                        'paddingRight' => ['value' => 0, 'unit' => 'px'],
                    ],
                ],
                styleCapabilities: ['display', 'width', 'maxWidth', 'minHeight', 'height', 'margin', 'padding', 'paddingTop', 'paddingRight', 'paddingBottom', 'paddingLeft', 'backgroundColor', 'backgroundType', 'backgroundGradient', 'backgroundImage', 'backgroundVideo', 'backgroundSize', 'backgroundPosition', 'backgroundRepeat', 'backgroundAttachment', 'backgroundOrigin', 'backgroundClip', 'backgroundBlendMode', 'position', 'borderWidth', 'borderStyle', 'borderColor', 'borderRadius', 'borderTopLeftRadius', 'borderTopRightRadius', 'borderBottomRightRadius', 'borderBottomLeftRadius', 'boxShadow', 'dropShadowX', 'dropShadowY', 'dropShadowBlur', 'dropShadowSpread', 'dropShadowColor', 'innerShadowX', 'innerShadowY', 'innerShadowBlur', 'innerShadowSpread', 'innerShadowColor', 'layerBlur', 'backgroundBlur', 'glassRefraction', 'glassDepth', 'glassDispersion', 'glassFrost', 'glassSplay', 'glassLightDegree', 'glassOpacity', 'filter', 'backdropFilter', 'mixBlendMode', 'opacity'],
                propSchema: [],
                childRules: [
                    'allowedTypes' => ['layout.row', 'layout.container', 'code.customcode'],
                ],
                integration: [
                    'rendererKey' => 'layout.section',
                    'editorKey' => 'layout.section',
                ],
            ),
            new ComponentDefinition(
                type: 'layout.row',
                name: 'Row',
                category: 'layout',
                description: 'Horizontal composition layer inside a Section.',
                capabilities: ['canHaveChildren' => true, 'canAcceptChildren' => true, 'supportsResponsiveStyles' => true],
                defaultStyles: ['desktop' => ['display' => 'flex', 'flexDirection' => 'row', 'width' => '1160px', 'maxWidth' => '100%', 'margin' => '0 auto', 'padding' => '10px', 'backgroundColor' => 'transparent', 'gap' => '16px', 'flexWrap' => 'nowrap']],
                styleCapabilities: ['display', 'width', 'minHeight', 'maxWidth', 'margin', 'padding', 'gap', 'flexDirection', 'justifyContent', 'alignItems', 'flexWrap', 'overflow', 'position', 'borderWidth', 'borderStyle', 'borderColor', 'borderRadius', 'borderTopLeftRadius', 'borderTopRightRadius', 'borderBottomRightRadius', 'borderBottomLeftRadius', 'boxShadow', 'dropShadowX', 'dropShadowY', 'dropShadowBlur', 'dropShadowSpread', 'dropShadowColor', 'innerShadowX', 'innerShadowY', 'innerShadowBlur', 'innerShadowSpread', 'innerShadowColor', 'layerBlur', 'backgroundBlur', 'glassRefraction', 'glassDepth', 'glassDispersion', 'glassFrost', 'glassSplay', 'glassLightDegree', 'glassOpacity', 'filter', 'backdropFilter', 'mixBlendMode', 'opacity', 'backgroundColor'],
                propSchema: ['fullWidth' => ['type' => 'boolean', 'label' => 'Full width']],
                childRules: ['allowedTypes' => ['layout.column', 'code.customcode']],
                integration: ['rendererKey' => 'layout.row', 'editorKey' => 'layout.row'],
            ),
            new ComponentDefinition(
                type: 'layout.column',
                name: 'Column',
                category: 'layout',
                description: 'Content container inside a Row.',
                capabilities: ['canHaveChildren' => true, 'canAcceptChildren' => true, 'supportsResponsiveStyles' => true],
                defaultStyles: ['desktop' => ['display' => 'flex', 'flexDirection' => 'column', 'gap' => '16px', 'width' => '1140px', 'maxWidth' => '100%', 'margin' => '0 auto', 'padding' => '10px', 'backgroundColor' => 'transparent']],
                styleCapabilities: ['display', 'width', 'minWidth', 'maxWidth', 'minHeight', 'margin', 'padding', 'gap', 'flexDirection', 'justifyContent', 'alignItems', 'flexWrap', 'overflow', 'position', 'borderWidth', 'borderStyle', 'borderColor', 'borderRadius', 'borderTopLeftRadius', 'borderTopRightRadius', 'borderBottomRightRadius', 'borderBottomLeftRadius', 'boxShadow', 'dropShadowX', 'dropShadowY', 'dropShadowBlur', 'dropShadowSpread', 'dropShadowColor', 'innerShadowX', 'innerShadowY', 'innerShadowBlur', 'innerShadowSpread', 'innerShadowColor', 'layerBlur', 'backgroundBlur', 'glassRefraction', 'glassDepth', 'glassDispersion', 'glassFrost', 'glassSplay', 'glassLightDegree', 'glassOpacity', 'filter', 'backdropFilter', 'mixBlendMode', 'opacity', 'backgroundColor'],
                propSchema: [],
                childRules: ['allowedTypes' => $columnChildren],
                integration: ['rendererKey' => 'layout.column', 'editorKey' => 'layout.column'],
            ),
            new ComponentDefinition(
                type: 'layout.container',
                name: 'Container',
                category: 'layout',
                description: 'Nested layout primitive for constraining and grouping child components.',
                capabilities: [
                    'canHaveChildren' => true,
                    'canAcceptChildren' => true,
                    'supportsResponsiveStyles' => true,
                ],
                defaultProps: [],
                defaultStyles: [
                    'desktop' => [
                        'maxWidth' => '900px',
                        'width' => '100%',
                        'display' => 'block',
                        'margin' => '0 auto',
                        'padding' => '10px',
                        'backgroundColor' => 'transparent',
                    ],
                ],
                styleCapabilities: ['display', 'width', 'maxWidth', 'margin', 'padding', 'gap', 'flexDirection', 'justifyContent', 'alignItems', 'flexWrap', 'overflow', 'position', 'borderWidth', 'borderStyle', 'borderColor', 'borderRadius', 'borderTopLeftRadius', 'borderTopRightRadius', 'borderBottomRightRadius', 'borderBottomLeftRadius', 'boxShadow', 'dropShadowX', 'dropShadowY', 'dropShadowBlur', 'dropShadowSpread', 'dropShadowColor', 'innerShadowX', 'innerShadowY', 'innerShadowBlur', 'innerShadowSpread', 'innerShadowColor', 'layerBlur', 'backgroundBlur', 'glassRefraction', 'glassDepth', 'glassDispersion', 'glassFrost', 'glassSplay', 'glassLightDegree', 'glassOpacity', 'filter', 'backdropFilter', 'mixBlendMode', 'opacity', 'backgroundColor'],
                propSchema: [],
                childRules: [
                    'allowedTypes' => $internalLayoutChildren,
                ],
                integration: [
                    'rendererKey' => 'layout.container',
                    'editorKey' => 'layout.container',
                ],
            ),
            new ComponentDefinition(
                type: 'layout.stack',
                name: 'Stack',
                category: 'layout',
                description: 'A vertical flow layout with consistent spacing.',
                capabilities: ['canHaveChildren' => true, 'canAcceptChildren' => true, 'supportsResponsiveStyles' => true],
                defaultStyles: ['desktop' => ['display' => 'flex', 'flexDirection' => 'column', 'gap' => '16px']],
                styleCapabilities: ['display', 'width', 'minHeight', 'maxWidth', 'margin', 'padding', 'gap', 'flexDirection', 'justifyContent', 'alignItems', 'flexWrap', 'backgroundColor'],
                childRules: ['allowedTypes' => $internalLayoutChildren],
                integration: ['rendererKey' => 'layout.stack', 'icon' => 'stack'],
            ),
            new ComponentDefinition(
                type: 'layout.flex',
                name: 'Flex',
                category: 'layout',
                description: 'A flexible row or column layout primitive.',
                capabilities: ['canHaveChildren' => true, 'canAcceptChildren' => true, 'supportsResponsiveStyles' => true],
                defaultStyles: ['desktop' => ['display' => 'flex', 'flexDirection' => 'row', 'gap' => '16px']],
                styleCapabilities: ['display', 'width', 'minHeight', 'maxWidth', 'margin', 'padding', 'gap', 'flexDirection', 'justifyContent', 'alignItems', 'flexWrap', 'backgroundColor'],
                childRules: ['allowedTypes' => ['layout.column', ...$internalLayoutChildren]],
                integration: ['rendererKey' => 'layout.flex', 'icon' => 'flex'],
            ),
            new ComponentDefinition(
                type: 'layout.grid',
                name: 'Grid',
                category: 'layout',
                description: 'A responsive grid for cards and repeated content.',
                capabilities: ['canHaveChildren' => true, 'canAcceptChildren' => true, 'supportsResponsiveStyles' => true],
                defaultStyles: ['desktop' => ['display' => 'grid', 'gridTemplateColumns' => 'repeat(3, minmax(0, 1fr))', 'gap' => '16px']],
                styleCapabilities: ['display', 'width', 'minHeight', 'maxWidth', 'margin', 'padding', 'gap', 'gridTemplateColumns', 'backgroundColor'],
                childRules: ['allowedTypes' => $internalLayoutChildren],
                integration: ['rendererKey' => 'layout.grid', 'icon' => 'grid'],
            ),
            new ComponentDefinition(
                type: 'layout.columns',
                name: 'Columns',
                category: 'layout',
                description: 'A simple multi-column composition primitive.',
                capabilities: ['canHaveChildren' => true, 'canAcceptChildren' => true, 'supportsResponsiveStyles' => true],
                defaultStyles: ['desktop' => ['display' => 'flex', 'flexDirection' => 'row', 'gap' => '16px']],
                styleCapabilities: ['display', 'width', 'minHeight', 'maxWidth', 'margin', 'padding', 'gap', 'flexDirection', 'justifyContent', 'alignItems', 'flexWrap'],
                childRules: ['allowedTypes' => $internalLayoutChildren],
                integration: ['rendererKey' => 'layout.columns', 'icon' => 'columns'],
            ),
            new ComponentDefinition(
                type: 'layout.spacer',
                name: 'Spacer',
                category: 'layout',
                description: 'Adds intentional vertical space to a composition.',
                capabilities: ['supportsResponsiveStyles' => true],
                defaultStyles: ['desktop' => ['minHeight' => '32px']],
                styleCapabilities: ['width', 'height', 'minHeight', 'maxHeight', 'margin'],
                childRules: ['allowedTypes' => []],
                integration: ['rendererKey' => 'layout.spacer', 'icon' => 'spacer'],
            ),
            new ComponentDefinition(
                type: 'layout.divider',
                name: 'Divider',
                category: 'layout',
                description: 'A visual separator between content groups.',
                capabilities: ['supportsResponsiveStyles' => true],
                defaultStyles: ['desktop' => ['borderWidth' => '1px', 'borderStyle' => 'solid', 'borderColor' => 'hsl(160 10% 88%)']],
                styleCapabilities: ['width', 'margin', 'borderWidth', 'borderStyle', 'borderColor'],
                childRules: ['allowedTypes' => []],
                integration: ['rendererKey' => 'layout.divider', 'icon' => 'divider'],
            ),
            new ComponentDefinition(
                type: 'content.heading',
                name: 'Heading',
                category: 'content',
                description: 'Text heading content primitive.',
                capabilities: [
                    'supportsText' => true,
                    'supportsResponsiveStyles' => true,
                ],
                defaultProps: [
                    'text' => 'Heading',
                    'level' => 2,
                    'colorSegments' => [],
                ],
                defaultStyles: [
                    'desktop' => [
                        'fontSize' => '32px',
                    ],
                ],
                styleCapabilities: ['display', 'maxWidth', 'margin', 'padding', 'color', 'fontFamily', 'fontSize', 'fontWeight', 'lineHeight', 'textAlign', 'overflowWrap', 'wordBreak'],
                propSchema: [
                    'text' => ['type' => 'string'],
                    'level' => ['type' => 'integer', 'min' => 1, 'max' => 6],
                    'colorSegments' => ['type' => 'array'],
                ],
                childRules: [
                    'allowedTypes' => [],
                ],
                integration: [
                    'rendererKey' => 'content.heading',
                    'editorKey' => 'content.heading',
                ],
            ),
            new ComponentDefinition(
                type: 'content.text',
                name: 'Text',
                category: 'content',
                description: 'A readable paragraph of body copy.',
                capabilities: ['supportsText' => true, 'supportsResponsiveStyles' => true],
                defaultProps: ['text' => 'Add a paragraph of text.', 'colorSegments' => []],
                defaultStyles: ['desktop' => ['fontSize' => '16px', 'lineHeight' => 1.6]],
                styleCapabilities: ['display', 'maxWidth', 'margin', 'padding', 'color', 'fontFamily', 'fontSize', 'fontWeight', 'lineHeight', 'letterSpacing', 'textTransform', 'textDecoration', 'textAlign', 'overflowWrap', 'wordBreak'],
                propSchema: ['text' => ['type' => 'string'], 'colorSegments' => ['type' => 'array']],
                childRules: ['allowedTypes' => []],
                integration: ['rendererKey' => 'content.text', 'icon' => 'text'],
            ),
            new ComponentDefinition(
                type: 'content.richtext',
                name: 'Rich Text',
                category: 'content',
                description: 'Structured editorial copy for longer content.',
                capabilities: ['supportsText' => true, 'supportsResponsiveStyles' => true],
                defaultProps: ['text' => 'Add rich text content.', 'colorSegments' => []],
                styleCapabilities: ['display', 'maxWidth', 'margin', 'padding', 'color', 'fontFamily', 'fontSize', 'fontWeight', 'lineHeight', 'letterSpacing', 'textTransform', 'textDecoration', 'textAlign', 'overflowWrap', 'wordBreak'],
                propSchema: ['text' => ['type' => 'string'], 'colorSegments' => ['type' => 'array']],
                childRules: ['allowedTypes' => []],
                integration: ['rendererKey' => 'content.richtext', 'icon' => 'rich-text'],
            ),
            new ComponentDefinition(
                type: 'content.button',
                name: 'Button',
                category: 'content',
                description: 'A clear action link for visitors.',
                capabilities: ['supportsText' => true, 'supportsResponsiveStyles' => true],
                defaultProps: ['text' => 'Get started', 'href' => '#'],
                defaultStyles: ['desktop' => ['display' => 'inline-block', 'padding' => '12px 16px', 'backgroundColor' => 'hsl(158 64% 32%)', 'color' => 'white', 'borderRadius' => '8px', 'textAlign' => 'center']],
                styleCapabilities: ['display', 'width', 'height', 'minWidth', 'maxWidth', 'minHeight', 'maxHeight', 'margin', 'padding', 'color', 'backgroundColor', 'fontFamily', 'fontSize', 'fontWeight', 'lineHeight', 'textAlign', 'overflowWrap', 'wordBreak', 'borderRadius', 'borderWidth', 'borderStyle', 'borderColor', 'boxShadow'],
                propSchema: [
                    'text' => ['type' => 'string'],
                    'href' => ['type' => 'string'],
                    'linkTarget' => ['type' => 'enum', 'values' => ['_self', '_blank']],
                    'linkType' => ['type' => 'string'],
                    'scrollTarget' => ['type' => 'string'],
                    'icon' => ['type' => 'string'],
                    'customIcon' => ['type' => 'string'],
                    'iconPosition' => ['type' => 'enum', 'values' => ['left', 'right']],
                    'iconSpacing' => ['type' => 'string'],
                    'iconSize' => ['type' => 'string'],
                    'showIcon' => ['type' => 'boolean'],
                ],
                childRules: ['allowedTypes' => []],
                integration: ['rendererKey' => 'content.button', 'icon' => 'button'],
            ),
            new ComponentDefinition(
                type: 'content.link',
                name: 'Link',
                category: 'content',
                description: 'A lightweight inline navigation link.',
                capabilities: ['supportsText' => true, 'supportsResponsiveStyles' => true],
                defaultProps: ['text' => 'Learn more', 'href' => '#'],
                styleCapabilities: ['display', 'maxWidth', 'margin', 'padding', 'color', 'fontFamily', 'fontSize', 'fontWeight', 'lineHeight', 'textDecoration', 'textAlign', 'overflowWrap', 'wordBreak'],
                propSchema: [
                    'text' => ['type' => 'string'],
                    'href' => ['type' => 'string'],
                    'linkTarget' => ['type' => 'enum', 'values' => ['_self', '_blank']],
                    'linkType' => ['type' => 'string'],
                    'scrollTarget' => ['type' => 'string'],
                ],
                childRules: ['allowedTypes' => []],
                integration: ['rendererKey' => 'content.link', 'icon' => 'link'],
            ),
            new ComponentDefinition(
                type: 'media.image',
                name: 'Image',
                category: 'media',
                description: 'An image reference with accessible alt text.',
                capabilities: ['supportsResponsiveStyles' => true],
                defaultProps: ['src' => '', 'alt' => ''],
                styleCapabilities: ['display', 'width', 'height', 'minWidth', 'maxWidth', 'margin', 'borderRadius', 'objectFit'],
                propSchema: ['src' => ['type' => 'string'], 'alt' => ['type' => 'string']],
                childRules: ['allowedTypes' => []],
                integration: ['rendererKey' => 'media.image', 'icon' => 'image'],
            ),
            new ComponentDefinition(
                type: 'code.customcode',
                name: 'Custom Code',
                category: 'code',
                description: 'Raw HTML with style and script tags, rendered as-is.',
                capabilities: ['supportsText' => true],
                defaultProps: ['code' => "<style>\n  /* your styles */\n</style>\n<script>\n  // your script\n</script>\n"],
                propSchema: ['code' => ['type' => 'string']],
                childRules: ['allowedTypes' => []],
                integration: ['rendererKey' => 'code.customcode', 'icon' => 'code'],
            ),
            new ComponentDefinition(
                type: 'marketing.card',
                name: 'Card',
                category: 'marketing',
                description: 'A contained surface for grouped content.',
                capabilities: ['canHaveChildren' => true, 'canAcceptChildren' => true, 'supportsResponsiveStyles' => true],
                defaultStyles: ['desktop' => ['display' => 'flex', 'flexDirection' => 'column', 'gap' => '12px', 'padding' => '24px', 'backgroundColor' => 'white', 'borderWidth' => '1px', 'borderStyle' => 'solid', 'borderColor' => 'hsl(160 10% 88%)', 'borderRadius' => '12px', 'boxShadow' => '0 1px 2px rgba(0,0,0,.08)']],
                styleCapabilities: ['display', 'width', 'minHeight', 'maxWidth', 'margin', 'padding', 'gap', 'flexDirection', 'justifyContent', 'alignItems', 'backgroundColor', 'borderWidth', 'borderStyle', 'borderColor', 'borderRadius', 'borderTopLeftRadius', 'borderTopRightRadius', 'borderBottomRightRadius', 'borderBottomLeftRadius', 'boxShadow'],
                childRules: ['allowedTypes' => $internalLayoutChildren],
                integration: ['rendererKey' => 'marketing.card', 'icon' => 'card'],
            ),
            new ComponentDefinition(
                type: 'reusable.instance',
                name: 'Reusable component',
                category: 'content',
                description: 'A reference to an owned reusable component definition.',
                capabilities: ['supportsResponsiveStyles' => false],
                defaultProps: [],
                defaultStyles: [],
                styleCapabilities: [],
                propSchema: [],
                childRules: ['allowedTypes' => []],
                integration: ['rendererKey' => 'reusable.instance'],
            ),
            new ComponentDefinition(
                type: 'layout.navbar',
                name: 'Header & Menu',
                category: 'layout',
                description: 'Responsive website header with brand, navigation links, CTA button, and mobile hamburger toggle.',
                capabilities: ['canHaveChildren' => false, 'canAcceptChildren' => false, 'supportsResponsiveStyles' => true],
                defaultProps: [
                    'brandName' => 'HelloWeb',
                    'brandLogo' => '',
                    'brandHref' => '/',
                    'links' => [
                        ['label' => 'Home', 'href' => '/'],
                        ['label' => 'Features', 'href' => '#features'],
                        ['label' => 'Pricing', 'href' => '#pricing'],
                        ['label' => 'About', 'href' => '#about'],
                    ],
                    'ctaText' => 'Get Started',
                    'ctaHref' => '#',
                    'showCta' => true,
                    'sticky' => false,
                ],
                defaultStyles: [
                    'desktop' => [
                        'display' => 'block',
                        'width' => '100%',
                        'backgroundColor' => 'transparent',
                        'color' => 'inherit',
                        'paddingTop' => ['value' => 16, 'unit' => 'px'],
                        'paddingBottom' => ['value' => 16, 'unit' => 'px'],
                        'paddingLeft' => ['value' => 24, 'unit' => 'px'],
                        'paddingRight' => ['value' => 24, 'unit' => 'px'],
                        'borderBottomWidth' => ['value' => 0, 'unit' => 'px'],
                        'borderBottomStyle' => 'solid',
                        'borderBottomColor' => 'transparent',
                    ],
                ],
                styleCapabilities: [
                    'display', 'overflow', 'width', 'maxWidth', 'minHeight', 'height', 'margin', 'marginTop', 'marginRight', 'marginBottom', 'marginLeft',
                    'padding', 'paddingTop', 'paddingRight', 'paddingBottom', 'paddingLeft', 'backgroundColor', 'color',
                    'borderWidth', 'borderTopWidth', 'borderRightWidth', 'borderBottomWidth', 'borderLeftWidth',
                    'borderStyle', 'borderTopStyle', 'borderRightStyle', 'borderBottomStyle', 'borderLeftStyle',
                    'borderColor', 'borderTopColor', 'borderRightColor', 'borderBottomColor', 'borderLeftColor',
                    'borderRadius', 'borderTopLeftRadius', 'borderTopRightRadius', 'borderBottomRightRadius', 'borderBottomLeftRadius',
                    'boxShadow', 'dropShadowX', 'dropShadowY', 'dropShadowBlur', 'dropShadowSpread', 'dropShadowColor',
                    'innerShadowX', 'innerShadowY', 'innerShadowBlur', 'innerShadowSpread', 'innerShadowColor',
                    'layerBlur', 'backgroundBlur',
                    'glassRefraction', 'glassDepth', 'glassDispersion', 'glassFrost', 'glassSplay', 'glassLightDegree', 'glassOpacity',
                    'filter', 'backdropFilter', 'mixBlendMode', 'opacity',
                    'position', 'top', 'bottom', 'left', 'right', 'zIndex',
                    'fontFamily', 'fontSize', 'fontWeight', 'lineHeight', 'letterSpacing', 'textAlign',
                    'justifyContent', 'alignItems', 'gap', 'flexDirection',
                ],
                propSchema: [
                    'brandName' => ['type' => 'string', 'label' => 'Brand Name'],
                    'brandLogo' => ['type' => 'string', 'label' => 'Logo Image URL'],
                    'brandHref' => ['type' => 'string', 'label' => 'Brand URL'],
                    'links' => ['type' => 'array', 'label' => 'Navigation Links'],
                    'ctaText' => ['type' => 'string', 'label' => 'CTA Button Text'],
                    'ctaHref' => ['type' => 'string', 'label' => 'CTA URL'],
                    'showCta' => ['type' => 'boolean', 'label' => 'Show CTA Button'],
                    'sticky' => ['type' => 'boolean', 'label' => 'Sticky Header'],
                ],
                childRules: ['allowedTypes' => []],
                integration: ['rendererKey' => 'layout.navbar'],
            ),
            new ComponentDefinition(
                type: 'marketing.blurb',
                name: 'Feature Box',
                category: 'marketing',
                description: 'Feature box highlighting a key capability with icon, title, description, and link.',
                capabilities: ['canHaveChildren' => false, 'canAcceptChildren' => false, 'supportsResponsiveStyles' => true],
                defaultProps: [
                    'icon' => 'sparkles',
                    'title' => 'Modern & Intuitive',
                    'description' => 'Empower your workflow with intuitive tools engineered for speed and aesthetic perfection.',
                    'linkText' => 'Learn more →',
                    'linkHref' => '#',
                    'iconColor' => '#2563eb',
                    'iconBg' => '#eff6ff',
                ],
                defaultStyles: [
                    'desktop' => [
                        'display' => 'flex',
                        'flexDirection' => 'column',
                        'alignItems' => 'flex-start',
                        'padding' => '24px',
                        'backgroundColor' => '#ffffff',
                        'borderRadius' => '12px',
                        'borderWidth' => '1px',
                        'borderStyle' => 'solid',
                        'borderColor' => '#e2e8f0',
                        'gap' => '12px',
                    ],
                ],
                styleCapabilities: ['display', 'width', 'maxWidth', 'margin', 'padding', 'gap', 'flexDirection', 'alignItems', 'justifyContent', 'backgroundColor', 'borderWidth', 'borderStyle', 'borderColor', 'borderRadius', 'boxShadow', 'opacity'],
                propSchema: [
                    'icon' => ['type' => 'string', 'label' => 'Icon'],
                    'customIcon' => ['type' => 'string', 'label' => 'Custom Icon'],
                    'title' => ['type' => 'string', 'label' => 'Title'],
                    'description' => ['type' => 'string', 'label' => 'Description'],
                    'linkText' => ['type' => 'string', 'label' => 'Link Text'],
                    'linkHref' => ['type' => 'string', 'label' => 'Link Destination'],
                    'iconColor' => ['type' => 'string', 'label' => 'Icon Color'],
                    'iconBg' => ['type' => 'string', 'label' => 'Icon Background Color'],
                    'iconPosition' => ['type' => 'enum', 'label' => 'Icon Position', 'values' => ['top', 'left']],
                    'iconShape' => ['type' => 'enum', 'label' => 'Icon Shape', 'values' => ['rounded', 'circle', 'square', 'none']],
                ],
                childRules: ['allowedTypes' => []],
                integration: ['rendererKey' => 'marketing.blurb'],
            ),
            new ComponentDefinition(
                type: 'content.list',
                name: 'Styled List',
                category: 'content',
                description: 'Styled list with checkmarks, bullet points, or numbered badges.',
                capabilities: ['canHaveChildren' => false, 'canAcceptChildren' => false, 'supportsResponsiveStyles' => true],
                defaultProps: [
                    'listType' => 'check',
                    'icon' => 'check',
                    'items' => [
                        'Lightning-fast page loading',
                        'Fully responsive on mobile & tablet',
                        'SEO optimized clean markup',
                        'One-click instant publishing',
                    ],
                    'iconColor' => '#10b981',
                ],
                defaultStyles: [
                    'desktop' => [
                        'display' => 'flex',
                        'flexDirection' => 'column',
                        'gap' => '12px',
                        'width' => '100%',
                        'margin' => '0',
                        'padding' => '0',
                    ],
                ],
                styleCapabilities: ['display', 'width', 'maxWidth', 'margin', 'padding', 'gap', 'flexDirection', 'alignItems', 'justifyContent', 'color', 'fontFamily', 'fontSize', 'fontWeight', 'lineHeight', 'letterSpacing', 'textAlign', 'overflowWrap', 'wordBreak', 'opacity'],
                propSchema: [
                    'listType' => ['type' => 'enum', 'label' => 'List Style', 'values' => ['check', 'bullet', 'number', 'icon']],
                    'icon' => ['type' => 'string', 'label' => 'Icon'],
                    'customIcon' => ['type' => 'string', 'label' => 'Custom Icon'],
                    'iconColor' => ['type' => 'string', 'label' => 'Icon / Bullet Color'],
                    'iconSize' => ['type' => 'string', 'label' => 'Icon Size'],
                    'items' => ['type' => 'array', 'label' => 'Items'],
                    'text' => ['type' => 'string', 'label' => 'Items (One per line)'],
                ],
                childRules: ['allowedTypes' => []],
                integration: ['rendererKey' => 'content.list'],
            ),
            new ComponentDefinition(
                type: 'marketing.pricing',
                name: 'Pricing Card',
                category: 'marketing',
                description: 'Responsive pricing plan card with badge, price, feature list, and call to action.',
                capabilities: ['canHaveChildren' => false, 'canAcceptChildren' => false, 'supportsResponsiveStyles' => true],
                defaultProps: [
                    'badge' => 'Most Popular',
                    'showBadge' => true,
                    'planName' => 'Pro',
                    'description' => 'Everything growing teams need to build, publish, and iterate faster.',
                    'price' => '$49',
                    'period' => '/ month',
                    'featureText' => "Unlimited published pages\nReusable sections and blocks\nCustom domains and SEO controls\nPriority framework updates",
                    'ctaText' => 'Start Building',
                    'ctaHref' => '#',
                    'accentColor' => '#2563eb',
                    'highlighted' => true,
                ],
                defaultStyles: [
                    'desktop' => [
                        'display' => 'block',
                        'width' => '100%',
                        'maxWidth' => '420px',
                        'margin' => '0 auto',
                        'padding' => '28px',
                        'backgroundColor' => '#ffffff',
                        'color' => '#0f172a',
                        'borderRadius' => '16px',
                        'borderWidth' => '1px',
                        'borderStyle' => 'solid',
                        'borderColor' => '#dbeafe',
                        'boxShadow' => '0 18px 40px rgba(15, 23, 42, 0.12)',
                        'overflowWrap' => 'anywhere',
                        'wordBreak' => 'normal',
                    ],
                    'tablet' => [
                        'maxWidth' => '100%',
                        'padding' => '24px',
                    ],
                    'mobile' => [
                        'maxWidth' => '100%',
                        'padding' => '20px',
                    ],
                ],
                styleCapabilities: ['display', 'width', 'maxWidth', 'margin', 'padding', 'backgroundColor', 'color', 'borderWidth', 'borderStyle', 'borderColor', 'borderRadius', 'boxShadow', 'overflowWrap', 'wordBreak', 'opacity'],
                propSchema: [
                    'badge' => ['type' => 'string', 'label' => 'Badge'],
                    'showBadge' => ['type' => 'boolean', 'label' => 'Show Badge'],
                    'planName' => ['type' => 'string', 'label' => 'Plan Name'],
                    'description' => ['type' => 'string', 'label' => 'Description'],
                    'price' => ['type' => 'string', 'label' => 'Price'],
                    'period' => ['type' => 'string', 'label' => 'Billing Period'],
                    'featureText' => ['type' => 'string', 'label' => 'Features (One per line)'],
                    'ctaText' => ['type' => 'string', 'label' => 'CTA Button Text'],
                    'ctaHref' => ['type' => 'string', 'label' => 'CTA URL'],
                    'accentColor' => ['type' => 'string', 'label' => 'Accent Color'],
                    'highlighted' => ['type' => 'boolean', 'label' => 'Highlighted'],
                ],
                childRules: ['allowedTypes' => []],
                integration: ['rendererKey' => 'marketing.pricing'],
            ),
            new ComponentDefinition(
                type: 'media.carousel',
                name: 'Image Carousel',
                category: 'media',
                description: 'Responsive horizontal carousel for product shots, portfolio images, or feature slides.',
                capabilities: ['canHaveChildren' => false, 'canAcceptChildren' => false, 'supportsResponsiveStyles' => true],
                defaultProps: ['slides' => [
                    ['src' => 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=80', 'title' => 'Workspace', 'caption' => 'A focused place to build.'],
                    ['src' => 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1200&q=80', 'title' => 'Studio', 'caption' => 'Creative systems that scale.'],
                    ['src' => 'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=1200&q=80', 'title' => 'Launch', 'caption' => 'Ship polished pages faster.'],
                ], 'accentColor' => '#2563eb', 'aspectRatio' => '16/9'],
                defaultStyles: ['desktop' => ['display' => 'block', 'width' => '100%', 'maxWidth' => '1140px', 'margin' => '0 auto', 'padding' => '0', 'borderRadius' => '16px', 'overflow' => 'hidden', 'backgroundColor' => '#f8fafc'], 'mobile' => ['maxWidth' => '100%', 'borderRadius' => '12px']],
                styleCapabilities: ['display', 'width', 'maxWidth', 'margin', 'padding', 'backgroundColor', 'borderRadius', 'boxShadow', 'overflow', 'opacity'],
                propSchema: ['slides' => ['type' => 'array', 'label' => 'Slides'], 'accentColor' => ['type' => 'string', 'label' => 'Accent Color'], 'aspectRatio' => ['type' => 'string', 'label' => 'Aspect Ratio']],
                childRules: ['allowedTypes' => []],
                integration: ['rendererKey' => 'media.carousel'],
            ),
            new ComponentDefinition(
                type: 'marketing.logomarquee',
                name: 'Logo Marquee',
                category: 'marketing',
                description: 'Animated logo strip for customers, partners, or integrations with controllable direction and colors.',
                capabilities: ['canHaveChildren' => false, 'canAcceptChildren' => false, 'supportsResponsiveStyles' => true],
                defaultProps: [
                    'logos' => [
                        ['src' => '/images/helloweb-logo-dark.png', 'alt' => 'HelloWeb', 'href' => '', 'name' => 'HelloWeb'],
                        ['src' => '/images/helloweb-logo-dark.png', 'alt' => 'Partner One', 'href' => '', 'name' => 'Partner One'],
                        ['src' => '/images/helloweb-logo-dark.png', 'alt' => 'Partner Two', 'href' => '', 'name' => 'Partner Two'],
                        ['src' => '/images/helloweb-logo-dark.png', 'alt' => 'Partner Three', 'href' => '', 'name' => 'Partner Three'],
                        ['src' => '/images/helloweb-logo-dark.png', 'alt' => 'Partner Four', 'href' => '', 'name' => 'Partner Four'],
                        ['src' => '/images/helloweb-logo-dark.png', 'alt' => 'Partner Five', 'href' => '', 'name' => 'Partner Five'],
                    ],
                    'direction' => 'left',
                    'speed' => '25s',
                    'pauseOnHover' => true,
                    'fadeEdges' => true,
                    'fadeWidth' => '80px',
                    'grayscale' => true,
                    'logoCardStyle' => 'card',
                    'logoBackground' => '#ffffff',
                    'borderColor' => '#e2e8f0',
                    'logoHeight' => '48px',
                    'itemHeight' => '64px',
                    'itemWidth' => 'auto',
                    'gap' => '24px',
                    'badgeShape' => 'rounded',
                    'objectFit' => 'contain',
                ],
                defaultStyles: ['desktop' => ['display' => 'block', 'width' => '100%', 'maxWidth' => '100%', 'margin' => '0 auto', 'padding' => '20px 0', 'backgroundColor' => 'transparent', 'overflow' => 'hidden'], 'mobile' => ['maxWidth' => '100%', 'padding' => '16px 0']],
                styleCapabilities: [
                    'display',
                    'width',
                    'maxWidth',
                    'margin',
                    'padding',
                    'backgroundColor',
                    'borderWidth',
                    'borderStyle',
                    'borderColor',
                    'borderRadius',
                    'borderTopLeftRadius',
                    'borderTopRightRadius',
                    'borderBottomRightRadius',
                    'borderBottomLeftRadius',
                    'boxShadow',
                    'dropShadowX',
                    'dropShadowY',
                    'dropShadowBlur',
                    'dropShadowSpread',
                    'dropShadowColor',
                    'innerShadowX',
                    'innerShadowY',
                    'innerShadowBlur',
                    'innerShadowSpread',
                    'innerShadowColor',
                    'layerBlur',
                    'backgroundBlur',
                    'filter',
                    'backdropFilter',
                    'overflow',
                    'opacity',
                ],
                propSchema: [
                    'logos' => ['type' => 'array', 'label' => 'Logo Images'],
                    'logoImages' => ['type' => 'string', 'label' => 'Logo Images (URL | Alt, one per line)'],
                    'direction' => ['type' => 'enum', 'label' => 'Direction', 'values' => ['left', 'right']],
                    'speed' => ['type' => 'string', 'label' => 'Speed'],
                    'pauseOnHover' => ['type' => 'boolean', 'label' => 'Pause On Hover'],
                    'fadeEdges' => ['type' => 'boolean', 'label' => 'Fade Edges'],
                    'fadeWidth' => ['type' => 'string', 'label' => 'Fade Width'],
                    'grayscale' => ['type' => 'boolean', 'label' => 'Grayscale'],
                    'logoCardStyle' => ['type' => 'enum', 'label' => 'Card Style', 'values' => ['card', 'clean']],
                    'badgeShape' => ['type' => 'enum', 'label' => 'Badge Shape', 'values' => ['rounded', 'pill', 'circle', 'square']],
                    'showPartnerNames' => ['type' => 'boolean', 'label' => 'Show Partner Names'],
                    'logoBackground' => ['type' => 'string', 'label' => 'Logo Background'],
                    'borderColor' => ['type' => 'string', 'label' => 'Border Color'],
                    'logoHeight' => ['type' => 'string', 'label' => 'Logo Height'],
                    'itemHeight' => ['type' => 'string', 'label' => 'Container Height'],
                    'itemWidth' => ['type' => 'string', 'label' => 'Container Width'],
                    'objectFit' => ['type' => 'enum', 'label' => 'Image Fit', 'values' => ['contain', 'cover']],
                    'gap' => ['type' => 'string', 'label' => 'Spacing Gap'],
                ],
                childRules: ['allowedTypes' => []],
                integration: ['rendererKey' => 'marketing.logomarquee'],
            ),
            new ComponentDefinition(
                type: 'content.accordion',
                name: 'Accordion',
                category: 'content',
                description: 'Responsive FAQ accordion with native expand/collapse behavior.',
                capabilities: ['canHaveChildren' => false, 'canAcceptChildren' => false, 'supportsResponsiveStyles' => true],
                defaultProps: ['items' => [
                    ['title' => 'Can I customize every section?', 'body' => 'Yes. Each element exposes responsive layout, spacing, color, and content controls.'],
                    ['title' => 'Does it work on mobile?', 'body' => 'The default structure uses responsive styles so content stacks and wraps on smaller screens.'],
                    ['title' => 'Can I publish fast?', 'body' => 'Pages render through the public renderer without loading the editor UI.'],
                ], 'accentColor' => '#2563eb'],
                defaultStyles: ['desktop' => ['display' => 'flex', 'flexDirection' => 'column', 'gap' => '10px', 'width' => '100%', 'maxWidth' => '760px', 'margin' => '0 auto', 'padding' => '0', 'color' => '#0f172a'], 'mobile' => ['maxWidth' => '100%']],
                styleCapabilities: ['display', 'width', 'maxWidth', 'margin', 'padding', 'gap', 'backgroundColor', 'color', 'fontFamily', 'borderRadius', 'opacity'],
                propSchema: ['items' => ['type' => 'array', 'label' => 'Items'], 'accentColor' => ['type' => 'string', 'label' => 'Accent Color']],
                childRules: ['allowedTypes' => []],
                integration: ['rendererKey' => 'content.accordion'],
            ),
            new ComponentDefinition(
                type: 'content.tabs',
                name: 'Tabs',
                category: 'content',
                description: 'Responsive tab-style content switcher rendered as accessible grouped panels.',
                capabilities: ['canHaveChildren' => false, 'canAcceptChildren' => false, 'supportsResponsiveStyles' => true],
                defaultProps: ['tabs' => [
                    ['label' => 'Design', 'body' => 'Compose pages from responsive primitives and reusable visual elements.'],
                    ['label' => 'Build', 'body' => 'Edit content, styles, and sections while preserving structured document data.'],
                    ['label' => 'Publish', 'body' => 'Render public pages without shipping the editor interface.'],
                ], 'accentColor' => '#2563eb'],
                defaultStyles: ['desktop' => ['display' => 'block', 'width' => '100%', 'maxWidth' => '860px', 'margin' => '0 auto', 'padding' => '0', 'color' => '#0f172a'], 'mobile' => ['maxWidth' => '100%']],
                styleCapabilities: ['display', 'width', 'maxWidth', 'margin', 'padding', 'backgroundColor', 'color', 'fontFamily', 'borderRadius', 'opacity'],
                propSchema: ['tabs' => ['type' => 'array', 'label' => 'Tabs'], 'accentColor' => ['type' => 'string', 'label' => 'Accent Color']],
                childRules: ['allowedTypes' => []],
                integration: ['rendererKey' => 'content.tabs'],
            ),
            new ComponentDefinition(
                type: 'marketing.stats',
                name: 'Stats',
                category: 'marketing',
                description: 'Responsive metric strip for numbers, outcomes, and social proof.',
                capabilities: ['canHaveChildren' => false, 'canAcceptChildren' => false, 'supportsResponsiveStyles' => true],
                defaultProps: ['stats' => [['value' => '99%', 'label' => 'Performance score'], ['value' => '4x', 'label' => 'Faster publishing'], ['value' => '24/7', 'label' => 'Global availability']], 'columnsDesktop' => 3, 'columnsTablet' => 3, 'columnsMobile' => 1, 'accentColor' => '#2563eb'],
                defaultStyles: ['desktop' => ['display' => 'block', 'width' => '100%', 'maxWidth' => '900px', 'margin' => '0 auto', 'padding' => '0', 'color' => '#0f172a'], 'mobile' => ['maxWidth' => '100%']],
                styleCapabilities: ['display', 'width', 'maxWidth', 'margin', 'padding', 'backgroundColor', 'color', 'fontFamily', 'borderRadius', 'opacity'],
                propSchema: ['stats' => ['type' => 'array', 'label' => 'Stats'], 'columnsDesktop' => ['type' => 'integer', 'label' => 'Desktop Columns', 'min' => 1, 'max' => 6], 'columnsTablet' => ['type' => 'integer', 'label' => 'Tablet Columns', 'min' => 1, 'max' => 4], 'columnsMobile' => ['type' => 'integer', 'label' => 'Mobile Columns', 'min' => 1, 'max' => 2], 'accentColor' => ['type' => 'string', 'label' => 'Accent Color']],
                childRules: ['allowedTypes' => []],
                integration: ['rendererKey' => 'marketing.stats'],
            ),
            new ComponentDefinition(
                type: 'marketing.testimonial',
                name: 'Testimonial',
                category: 'marketing',
                description: 'Customer quote card with author details and accent color.',
                capabilities: ['canHaveChildren' => false, 'canAcceptChildren' => false, 'supportsResponsiveStyles' => true],
                defaultProps: ['quote' => 'HelloWeb gave our team the structure of a framework with the speed of a visual builder.', 'author' => 'Maya Chen', 'role' => 'Founder, Northstar Studio', 'accentColor' => '#2563eb'],
                defaultStyles: ['desktop' => ['display' => 'block', 'width' => '100%', 'maxWidth' => '720px', 'margin' => '0 auto', 'padding' => '28px', 'backgroundColor' => '#ffffff', 'color' => '#0f172a', 'borderRadius' => '16px', 'borderWidth' => '1px', 'borderStyle' => 'solid', 'borderColor' => '#e2e8f0', 'boxShadow' => '0 12px 30px rgba(15, 23, 42, 0.08)', 'overflowWrap' => 'anywhere'], 'mobile' => ['maxWidth' => '100%', 'padding' => '20px']],
                styleCapabilities: ['display', 'width', 'maxWidth', 'margin', 'padding', 'backgroundColor', 'color', 'borderWidth', 'borderStyle', 'borderColor', 'borderRadius', 'boxShadow', 'overflowWrap', 'opacity'],
                propSchema: ['quote' => ['type' => 'string', 'label' => 'Quote'], 'author' => ['type' => 'string', 'label' => 'Author'], 'role' => ['type' => 'string', 'label' => 'Role'], 'accentColor' => ['type' => 'string', 'label' => 'Accent Color']],
                childRules: ['allowedTypes' => []],
                integration: ['rendererKey' => 'marketing.testimonial'],
            ),
            new ComponentDefinition(
                type: 'embed.video',
                name: 'Video Embed',
                category: 'media',
                description: 'Responsive video embed for YouTube, Vimeo, or direct iframe URLs.',
                capabilities: ['canHaveChildren' => false, 'canAcceptChildren' => false, 'supportsResponsiveStyles' => true],
                defaultProps: ['src' => 'https://www.youtube.com/embed/dQw4w9WgXcQ', 'title' => 'Embedded video', 'aspectRatio' => '16/9'],
                defaultStyles: ['desktop' => ['display' => 'block', 'width' => '100%', 'maxWidth' => '900px', 'margin' => '0 auto', 'padding' => '0', 'borderRadius' => '16px', 'overflow' => 'hidden', 'backgroundColor' => '#020617'], 'mobile' => ['maxWidth' => '100%', 'borderRadius' => '12px']],
                styleCapabilities: ['display', 'width', 'maxWidth', 'margin', 'padding', 'backgroundColor', 'borderRadius', 'overflow', 'opacity'],
                propSchema: ['src' => ['type' => 'string', 'label' => 'Embed URL'], 'title' => ['type' => 'string', 'label' => 'Title'], 'aspectRatio' => ['type' => 'string', 'label' => 'Aspect Ratio']],
                childRules: ['allowedTypes' => []],
                integration: ['rendererKey' => 'embed.video'],
            ),
            new ComponentDefinition(
                type: 'form.contact',
                name: 'Contact Form',
                category: 'form',
                description: 'Responsive contact form shell with editable labels and accent color.',
                capabilities: ['canHaveChildren' => false, 'canAcceptChildren' => false, 'supportsResponsiveStyles' => true],
                defaultProps: ['title' => 'Contact us', 'description' => 'Tell us what you want to build and we will get back to you.', 'nameLabel' => 'Name', 'emailLabel' => 'Email', 'messageLabel' => 'Message', 'buttonText' => 'Send Message', 'accentColor' => '#2563eb'],
                defaultStyles: ['desktop' => ['display' => 'block', 'width' => '100%', 'maxWidth' => '680px', 'margin' => '0 auto', 'padding' => '28px', 'backgroundColor' => '#ffffff', 'color' => '#0f172a', 'borderRadius' => '16px', 'borderWidth' => '1px', 'borderStyle' => 'solid', 'borderColor' => '#e2e8f0', 'boxShadow' => '0 12px 30px rgba(15, 23, 42, 0.08)'], 'mobile' => ['maxWidth' => '100%', 'padding' => '20px']],
                styleCapabilities: ['display', 'width', 'maxWidth', 'margin', 'padding', 'backgroundColor', 'color', 'borderWidth', 'borderStyle', 'borderColor', 'borderRadius', 'boxShadow', 'opacity'],
                propSchema: ['title' => ['type' => 'string', 'label' => 'Title'], 'description' => ['type' => 'string', 'label' => 'Description'], 'nameLabel' => ['type' => 'string', 'label' => 'Name Label'], 'emailLabel' => ['type' => 'string', 'label' => 'Email Label'], 'messageLabel' => ['type' => 'string', 'label' => 'Message Label'], 'buttonText' => ['type' => 'string', 'label' => 'Button Text'], 'accentColor' => ['type' => 'string', 'label' => 'Accent Color']],
                childRules: ['allowedTypes' => []],
                integration: ['rendererKey' => 'form.contact'],
            ),
            new ComponentDefinition(
                type: 'marketing.imagefeature',
                name: 'Image Feature',
                category: 'marketing',
                description: 'Split section pairing compelling copy and CTA with a prominent visual image.',
                capabilities: ['canHaveChildren' => false, 'canAcceptChildren' => false, 'supportsResponsiveStyles' => true],
                defaultProps: [
                    'badge' => 'FEATURE HIGHLIGHT',
                    'showBadge' => true,
                    'title' => 'Design at the speed of thought',
                    'showTitle' => true,
                    'description' => 'Create responsive, production-ready websites with a powerful visual editor built for modern teams.',
                    'showDescription' => true,
                    'imageSrc' => 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80',
                    'imageAlt' => 'Feature preview',
                    'imagePosition' => 'right',
                    'ctaText' => 'Explore Platform',
                    'ctaHref' => '#',
                    'showCta' => true,
                    'cardStyle' => true,
                    'buttonPosition' => 'bottom',
                ],
                defaultStyles: [
                    'desktop' => [
                        'display' => 'block',
                        'width' => '100%',
                        'backgroundColor' => '#ffffff',
                        'borderRadius' => '16px',
                        'borderWidth' => '1px',
                        'borderStyle' => 'solid',
                        'borderColor' => '#e2e8f0',
                        'padding' => '32px',
                        'boxShadow' => '0 1px 2px rgba(0,0,0,.08)',
                        'margin' => '0 auto',
                        'maxWidth' => '1140px',
                    ],
                ],
                styleCapabilities: ['display', 'width', 'maxWidth', 'margin', 'padding', 'backgroundColor', 'borderWidth', 'borderStyle', 'borderColor', 'borderRadius', 'boxShadow', 'opacity'],
                propSchema: [
                    'badge' => ['type' => 'string', 'label' => 'Badge'],
                    'showBadge' => ['type' => 'boolean', 'label' => 'Show Badge'],
                    'title' => ['type' => 'string', 'label' => 'Title'],
                    'showTitle' => ['type' => 'boolean', 'label' => 'Show Title'],
                    'description' => ['type' => 'string', 'label' => 'Description'],
                    'showDescription' => ['type' => 'boolean', 'label' => 'Show Description'],
                    'imageSrc' => ['type' => 'string', 'label' => 'Image URL'],
                    'imageAlt' => ['type' => 'string', 'label' => 'Image Alt'],
                    'imagePosition' => ['type' => 'enum', 'label' => 'Image Position', 'values' => ['left', 'right', 'top', 'bottom']],
                    'ctaText' => ['type' => 'string', 'label' => 'CTA Button Text'],
                    'ctaHref' => ['type' => 'string', 'label' => 'CTA URL'],
                    'showCta' => ['type' => 'boolean', 'label' => 'Show CTA Button'],
                    'cardStyle' => ['type' => 'boolean', 'label' => 'Display as Card'],
                    'buttonPosition' => ['type' => 'enum', 'label' => 'Button Position', 'values' => ['bottom', 'inline']],
                ],
                childRules: ['allowedTypes' => []],
                integration: ['rendererKey' => 'marketing.imagefeature'],
            ),
            new ComponentDefinition(
                type: 'media.gallery',
                name: 'Image Gallery',
                category: 'media',
                description: 'Responsive photo gallery with interactive full-screen lightbox preview.',
                capabilities: ['canHaveChildren' => false, 'canAcceptChildren' => false, 'supportsResponsiveStyles' => true],
                defaultProps: [
                    'columns' => 3,
                    'columnsDesktop' => 3,
                    'columnsTablet' => 2,
                    'columnsMobile' => 1,
                    'gap' => '16px',
                    'gapDesktop' => '16px',
                    'gapTablet' => '12px',
                    'gapMobile' => '8px',
                    'aspectRatio' => '4/3',
                    'images' => [
                        ['src' => 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80', 'caption' => 'Tropical Paradise'],
                        ['src' => 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=800&q=80', 'caption' => 'Misty Mountains'],
                        ['src' => 'https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?auto=format&fit=crop&w=800&q=80', 'caption' => 'Forest Canopy'],
                        ['src' => 'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?auto=format&fit=crop&w=800&q=80', 'caption' => 'Desert Dunes'],
                        ['src' => 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=800&q=80', 'caption' => 'Wilderness Vista'],
                        ['src' => 'https://images.unsplash.com/photo-1433086966358-54859d0ed716?auto=format&fit=crop&w=800&q=80', 'caption' => 'Cascading Falls'],
                    ],
                ],
                defaultStyles: [
                    'desktop' => [
                        'display' => 'block',
                        'width' => '100%',
                        'margin' => '0 auto',
                        'padding' => '16px 0',
                        'maxWidth' => '1140px',
                    ],
                ],
                styleCapabilities: ['display', 'width', 'maxWidth', 'margin', 'padding', 'opacity'],
                propSchema: [
                    'columns' => ['type' => 'integer', 'label' => 'Columns'],
                    'columnsDesktop' => ['type' => 'integer', 'label' => 'Desktop Columns'],
                    'columnsTablet' => ['type' => 'integer', 'label' => 'Tablet Columns'],
                    'columnsMobile' => ['type' => 'integer', 'label' => 'Mobile Columns'],
                    'gap' => ['type' => 'string', 'label' => 'Grid Gap'],
                    'gapDesktop' => ['type' => 'string', 'label' => 'Desktop Gap'],
                    'gapTablet' => ['type' => 'string', 'label' => 'Tablet Gap'],
                    'gapMobile' => ['type' => 'string', 'label' => 'Mobile Gap'],
                    'aspectRatio' => ['type' => 'string', 'label' => 'Aspect Ratio'],
                    'images' => ['type' => 'array', 'label' => 'Gallery Images'],
                ],
                childRules: ['allowedTypes' => []],
                integration: ['rendererKey' => 'media.gallery'],
            ),
            new ComponentDefinition(
                type: 'marketing.countdown',
                name: 'Countdown Timer',
                category: 'marketing',
                description: 'Urgency countdown timer for sales, product launches, events, and limited-time promotions.',
                capabilities: ['canHaveChildren' => false, 'canAcceptChildren' => false, 'supportsResponsiveStyles' => true],
                defaultProps: [
                    'targetDate' => '2026-12-31T23:59:59',
                    'styleVariant' => 'card',
                    'showDays' => true,
                    'showHours' => true,
                    'showMinutes' => true,
                    'showSeconds' => true,
                    'labelDays' => 'Days',
                    'labelHours' => 'Hours',
                    'labelMinutes' => 'Minutes',
                    'labelSeconds' => 'Seconds',
                    'digitColor' => '#0f172a',
                    'labelColor' => '#64748b',
                    'cardBackground' => '#ffffff',
                    'cardBorderColor' => '#e2e8f0',
                    'accentColor' => '#2563eb',
                    'expiryText' => 'Special offer has ended!',
                ],
                defaultStyles: [
                    'desktop' => ['display' => 'block', 'width' => '100%', 'maxWidth' => '640px', 'margin' => '0 auto', 'padding' => '16px 0', 'backgroundColor' => 'transparent'],
                    'mobile' => ['maxWidth' => '100%', 'padding' => '10px 0'],
                ],
                styleCapabilities: ['display', 'width', 'maxWidth', 'margin', 'padding', 'backgroundColor', 'borderRadius', 'boxShadow', 'opacity'],
                propSchema: [
                    'targetDate' => ['type' => 'string', 'label' => 'Target Date & Time'],
                    'styleVariant' => ['type' => 'enum', 'label' => 'Display Style', 'values' => ['card', 'minimal', 'circle']],
                    'showDays' => ['type' => 'boolean', 'label' => 'Show Days'],
                    'showHours' => ['type' => 'boolean', 'label' => 'Show Hours'],
                    'showMinutes' => ['type' => 'boolean', 'label' => 'Show Minutes'],
                    'showSeconds' => ['type' => 'boolean', 'label' => 'Show Seconds'],
                    'labelDays' => ['type' => 'string', 'label' => 'Days Label'],
                    'labelHours' => ['type' => 'string', 'label' => 'Hours Label'],
                    'labelMinutes' => ['type' => 'string', 'label' => 'Minutes Label'],
                    'labelSeconds' => ['type' => 'string', 'label' => 'Seconds Label'],
                    'digitColor' => ['type' => 'string', 'label' => 'Digit Color'],
                    'labelColor' => ['type' => 'string', 'label' => 'Label Color'],
                    'cardBackground' => ['type' => 'string', 'label' => 'Card Background'],
                    'cardBorderColor' => ['type' => 'string', 'label' => 'Card Border Color'],
                    'accentColor' => ['type' => 'string', 'label' => 'Accent Color'],
                    'expiryText' => ['type' => 'string', 'label' => 'Expiration Message'],
                ],
                childRules: ['allowedTypes' => []],
                integration: ['rendererKey' => 'marketing.countdown'],
            ),
            new ComponentDefinition(
                type: 'content.socialicons',
                name: 'Social Icons',
                category: 'content',
                description: 'Connect with visitors via styled social profile links with brand or custom colors.',
                capabilities: ['canHaveChildren' => false, 'canAcceptChildren' => false, 'supportsResponsiveStyles' => true],
                defaultProps: [
                    'items' => [
                        ['platform' => 'facebook', 'url' => 'https://facebook.com', 'label' => 'Facebook'],
                        ['platform' => 'twitter', 'url' => 'https://x.com', 'label' => 'X (Twitter)'],
                        ['platform' => 'instagram', 'url' => 'https://instagram.com', 'label' => 'Instagram'],
                        ['platform' => 'linkedin', 'url' => 'https://linkedin.com', 'label' => 'LinkedIn'],
                        ['platform' => 'youtube', 'url' => 'https://youtube.com', 'label' => 'YouTube'],
                        ['platform' => 'github', 'url' => 'https://github.com', 'label' => 'GitHub'],
                    ],
                    'iconStyle' => 'brand',
                    'shape' => 'circle',
                    'size' => 'md',
                    'align' => 'center',
                    'customColor' => '#2563eb',
                    'customBg' => '#eff6ff',
                    'openInNewTab' => true,
                    'gap' => '12px',
                ],
                defaultStyles: [
                    'desktop' => ['display' => 'block', 'width' => '100%', 'margin' => '0 auto', 'padding' => '8px 0', 'backgroundColor' => 'transparent'],
                ],
                styleCapabilities: ['display', 'width', 'maxWidth', 'margin', 'padding', 'backgroundColor', 'opacity'],
                propSchema: [
                    'items' => ['type' => 'array', 'label' => 'Social Networks'],
                    'iconStyle' => ['type' => 'enum', 'label' => 'Icon Style', 'values' => ['brand', 'monochrome', 'outline']],
                    'shape' => ['type' => 'enum', 'label' => 'Shape', 'values' => ['circle', 'rounded', 'square']],
                    'size' => ['type' => 'enum', 'label' => 'Icon Size', 'values' => ['sm', 'md', 'lg']],
                    'align' => ['type' => 'enum', 'label' => 'Alignment', 'values' => ['left', 'center', 'right']],
                    'customColor' => ['type' => 'string', 'label' => 'Monochrome Icon Color'],
                    'customBg' => ['type' => 'string', 'label' => 'Monochrome Background Color'],
                    'openInNewTab' => ['type' => 'boolean', 'label' => 'Open In New Tab'],
                    'gap' => ['type' => 'string', 'label' => 'Spacing Between Icons'],
                ],
                childRules: ['allowedTypes' => []],
                integration: ['rendererKey' => 'content.socialicons'],
            ),
            new ComponentDefinition(
                type: 'content.alert',
                name: 'Alert Banner',
                category: 'content',
                description: 'Notice callout for announcements, tips, warnings, and updates with optional action button.',
                capabilities: ['canHaveChildren' => false, 'canAcceptChildren' => false, 'supportsResponsiveStyles' => true],
                defaultProps: [
                    'variant' => 'info',
                    'title' => 'Special Announcement',
                    'message' => 'Discover our newest platform features and explore customizable components.',
                    'showIcon' => true,
                    'actionText' => 'Learn more →',
                    'actionHref' => '#',
                    'dismissible' => false,
                ],
                defaultStyles: [
                    'desktop' => ['display' => 'block', 'width' => '100%', 'maxWidth' => '860px', 'margin' => '0 auto', 'padding' => '16px', 'borderRadius' => '12px', 'backgroundColor' => '#eff6ff', 'borderWidth' => '1px', 'borderStyle' => 'solid', 'borderColor' => '#bfdbfe'],
                    'mobile' => ['maxWidth' => '100%', 'padding' => '14px'],
                ],
                styleCapabilities: ['display', 'width', 'maxWidth', 'margin', 'padding', 'backgroundColor', 'borderColor', 'borderRadius', 'boxShadow', 'opacity'],
                propSchema: [
                    'variant' => ['type' => 'enum', 'label' => 'Banner Type', 'values' => ['info', 'success', 'warning', 'destructive', 'neutral']],
                    'title' => ['type' => 'string', 'label' => 'Title'],
                    'message' => ['type' => 'string', 'label' => 'Message'],
                    'showIcon' => ['type' => 'boolean', 'label' => 'Show Icon'],
                    'actionText' => ['type' => 'string', 'label' => 'Action Button Text'],
                    'actionHref' => ['type' => 'string', 'label' => 'Action URL'],
                    'dismissible' => ['type' => 'boolean', 'label' => 'Dismissible'],
                ],
                childRules: ['allowedTypes' => []],
                integration: ['rendererKey' => 'content.alert'],
            ),
            new ComponentDefinition(
                type: 'marketing.progressbar',
                name: 'Progress Bar',
                category: 'marketing',
                description: 'Visual progress indicator for skills, fundraising goals, milestones, or project completion.',
                capabilities: ['canHaveChildren' => false, 'canAcceptChildren' => false, 'supportsResponsiveStyles' => true],
                defaultProps: [
                    'label' => 'Project Completion',
                    'percentage' => 85,
                    'showPercentage' => true,
                    'barHeight' => '12px',
                    'barColor' => '#2563eb',
                    'trackColor' => '#e2e8f0',
                    'striped' => false,
                    'animated' => false,
                    'borderRadius' => '9999px',
                ],
                defaultStyles: [
                    'desktop' => ['display' => 'block', 'width' => '100%', 'maxWidth' => '720px', 'margin' => '0 auto', 'padding' => '12px 0', 'backgroundColor' => 'transparent'],
                    'mobile' => ['maxWidth' => '100%'],
                ],
                styleCapabilities: ['display', 'width', 'maxWidth', 'margin', 'padding', 'backgroundColor', 'opacity'],
                propSchema: [
                    'label' => ['type' => 'string', 'label' => 'Progress Label'],
                    'percentage' => ['type' => 'integer', 'label' => 'Percentage (0 - 100)', 'min' => 0, 'max' => 100],
                    'showPercentage' => ['type' => 'boolean', 'label' => 'Show Percentage Text'],
                    'barHeight' => ['type' => 'string', 'label' => 'Bar Height'],
                    'barColor' => ['type' => 'string', 'label' => 'Fill Bar Color'],
                    'trackColor' => ['type' => 'string', 'label' => 'Background Track Color'],
                    'striped' => ['type' => 'boolean', 'label' => 'Striped Pattern'],
                    'animated' => ['type' => 'boolean', 'label' => 'Animated Stripes'],
                    'borderRadius' => ['type' => 'string', 'label' => 'Corner Radius'],
                ],
                childRules: ['allowedTypes' => []],
                integration: ['rendererKey' => 'marketing.progressbar'],
            ),
        ];
    }

    public static function registry(): ComponentRegistry
    {
        return new ComponentRegistry(self::all());
    }
}
