<?php

namespace App\Builder\Registry;

use App\Builder\Component\ComponentDefinition;

final class BuiltInComponentDefinitions
{
    /**
     * @return list<ComponentDefinition>
     */
    public static function all(): array
    {
        $columnChildren = [
            'layout.row', 'layout.container', 'layout.stack', 'layout.flex', 'layout.grid', 'layout.columns', 'layout.spacer', 'layout.divider', 'layout.navbar',
            'content.heading', 'content.text', 'content.richtext', 'content.button', 'content.link', 'content.list', 'media.image', 'media.gallery', 'code.customcode', 'marketing.card', 'marketing.blurb', 'marketing.imagefeature', 'reusable.instance',
        ];
        $internalLayoutChildren = $columnChildren;

        return [
            new ComponentDefinition(
                type: 'layout.root',
                name: 'Root',
                category: 'layout',
                description: 'Structural document root for rendering top-level page sections.',
                capabilities: [
                    'canHaveChildren' => true,
                    'canAcceptChildren' => true,
                    'supportsResponsiveStyles' => false,
                ],
                defaultProps: [],
                defaultStyles: [],
                styleCapabilities: [],
                propSchema: [],
                childRules: [
                    'allowedTypes' => ['layout.section', 'layout.navbar'],
                ],
                integration: [
                    'rendererKey' => 'layout.root',
                ],
            ),
            new ComponentDefinition(
                type: 'layout.section',
                name: 'Section',
                category: 'layout',
                description: 'Top-level page section for grouping layout and content nodes.',
                capabilities: [
                    'canHaveChildren' => true,
                    'canAcceptChildren' => true,
                    'supportsResponsiveStyles' => true,
                ],
                defaultProps: [],
                defaultStyles: [
                    'desktop' => [
                        'display' => 'block',
                        'width' => '100%',
                        'minHeight' => '50px',
                        'position' => 'relative',
                        'margin' => '0 auto',
                        'padding' => '10px',
                        'backgroundColor' => 'transparent',
                        'paddingTop' => ['value' => 10, 'unit' => 'px'],
                        'paddingBottom' => ['value' => 10, 'unit' => 'px'],
                        'paddingLeft' => ['value' => 0, 'unit' => 'px'],
                        'paddingRight' => ['value' => 0, 'unit' => 'px'],
                    ],
                ],
                styleCapabilities: ['display', 'width', 'maxWidth', 'minHeight', 'height', 'margin', 'padding', 'paddingTop', 'paddingRight', 'paddingBottom', 'paddingLeft', 'backgroundColor', 'backgroundType', 'backgroundGradient', 'backgroundImage', 'backgroundVideo', 'backgroundSize', 'backgroundPosition', 'backgroundRepeat', 'backgroundAttachment', 'backgroundOrigin', 'backgroundClip', 'backgroundBlendMode', 'position', 'borderWidth', 'borderStyle', 'borderColor', 'borderRadius', 'borderTopLeftRadius', 'borderTopRightRadius', 'borderBottomRightRadius', 'borderBottomLeftRadius', 'boxShadow', 'dropShadowX', 'dropShadowY', 'dropShadowBlur', 'dropShadowSpread', 'dropShadowColor', 'innerShadowX', 'innerShadowY', 'innerShadowBlur', 'innerShadowSpread', 'innerShadowColor', 'layerBlur', 'backgroundBlur', 'glassRefraction', 'glassDepth', 'glassDispersion', 'glassFrost', 'glassSplay', 'glassLightDegree', 'glassOpacity', 'filter', 'backdropFilter', 'mixBlendMode', 'opacity'],
                propSchema: [],
                childRules: [
                    'allowedTypes' => ['layout.row', 'layout.container', 'code.customcode'],
                ],
                integration: [
                    'rendererKey' => 'layout.section',
                    'editorKey' => 'layout.section',
                ],
            ),
            new ComponentDefinition(
                type: 'layout.row',
                name: 'Row',
                category: 'layout',
                description: 'Horizontal composition layer inside a Section.',
                capabilities: ['canHaveChildren' => true, 'canAcceptChildren' => true, 'supportsResponsiveStyles' => true],
                defaultStyles: ['desktop' => ['display' => 'flex', 'flexDirection' => 'row', 'width' => '100%', 'maxWidth' => '1140px', 'margin' => '0 auto', 'padding' => '10px', 'backgroundColor' => 'transparent', 'gap' => '16px', 'flexWrap' => 'nowrap']],
                styleCapabilities: ['display', 'width', 'minHeight', 'maxWidth', 'margin', 'padding', 'gap', 'flexDirection', 'justifyContent', 'alignItems', 'flexWrap', 'overflow', 'position', 'borderWidth', 'borderStyle', 'borderColor', 'borderRadius', 'borderTopLeftRadius', 'borderTopRightRadius', 'borderBottomRightRadius', 'borderBottomLeftRadius', 'boxShadow', 'dropShadowX', 'dropShadowY', 'dropShadowBlur', 'dropShadowSpread', 'dropShadowColor', 'innerShadowX', 'innerShadowY', 'innerShadowBlur', 'innerShadowSpread', 'innerShadowColor', 'layerBlur', 'backgroundBlur', 'glassRefraction', 'glassDepth', 'glassDispersion', 'glassFrost', 'glassSplay', 'glassLightDegree', 'glassOpacity', 'filter', 'backdropFilter', 'mixBlendMode', 'opacity', 'backgroundColor'],
                propSchema: ['fullWidth' => ['type' => 'boolean', 'label' => 'Full width']],
                childRules: ['allowedTypes' => ['layout.column', 'code.customcode']],
                integration: ['rendererKey' => 'layout.row', 'editorKey' => 'layout.row'],
            ),
            new ComponentDefinition(
                type: 'layout.column',
                name: 'Column',
                category: 'layout',
                description: 'Content container inside a Row.',
                capabilities: ['canHaveChildren' => true, 'canAcceptChildren' => true, 'supportsResponsiveStyles' => true],
                defaultStyles: ['desktop' => ['display' => 'flex', 'flexDirection' => 'column', 'gap' => '16px', 'width' => '100%', 'maxWidth' => '900px', 'margin' => '0 auto', 'padding' => '10px', 'backgroundColor' => 'transparent']],
                styleCapabilities: ['display', 'width', 'minWidth', 'maxWidth', 'minHeight', 'margin', 'padding', 'gap', 'flexDirection', 'justifyContent', 'alignItems', 'flexWrap', 'overflow', 'position', 'borderWidth', 'borderStyle', 'borderColor', 'borderRadius', 'borderTopLeftRadius', 'borderTopRightRadius', 'borderBottomRightRadius', 'borderBottomLeftRadius', 'boxShadow', 'dropShadowX', 'dropShadowY', 'dropShadowBlur', 'dropShadowSpread', 'dropShadowColor', 'innerShadowX', 'innerShadowY', 'innerShadowBlur', 'innerShadowSpread', 'innerShadowColor', 'layerBlur', 'backgroundBlur', 'glassRefraction', 'glassDepth', 'glassDispersion', 'glassFrost', 'glassSplay', 'glassLightDegree', 'glassOpacity', 'filter', 'backdropFilter', 'mixBlendMode', 'opacity', 'backgroundColor'],
                propSchema: [],
                childRules: ['allowedTypes' => $columnChildren],
                integration: ['rendererKey' => 'layout.column', 'editorKey' => 'layout.column'],
            ),
            new ComponentDefinition(
                type: 'layout.container',
                name: 'Container',
                category: 'layout',
                description: 'Nested layout primitive for constraining and grouping child components.',
                capabilities: [
                    'canHaveChildren' => true,
                    'canAcceptChildren' => true,
                    'supportsResponsiveStyles' => true,
                ],
                defaultProps: [],
                defaultStyles: [
                    'desktop' => [
                        'maxWidth' => '900px',
                        'width' => '100%',
                        'display' => 'block',
                        'margin' => '0 auto',
                        'padding' => '10px',
                        'backgroundColor' => 'transparent',
                    ],
                ],
                styleCapabilities: ['display', 'width', 'maxWidth', 'margin', 'padding', 'gap', 'flexDirection', 'justifyContent', 'alignItems', 'flexWrap', 'overflow', 'position', 'borderWidth', 'borderStyle', 'borderColor', 'borderRadius', 'borderTopLeftRadius', 'borderTopRightRadius', 'borderBottomRightRadius', 'borderBottomLeftRadius', 'boxShadow', 'dropShadowX', 'dropShadowY', 'dropShadowBlur', 'dropShadowSpread', 'dropShadowColor', 'innerShadowX', 'innerShadowY', 'innerShadowBlur', 'innerShadowSpread', 'innerShadowColor', 'layerBlur', 'backgroundBlur', 'glassRefraction', 'glassDepth', 'glassDispersion', 'glassFrost', 'glassSplay', 'glassLightDegree', 'glassOpacity', 'filter', 'backdropFilter', 'mixBlendMode', 'opacity', 'backgroundColor'],
                propSchema: [],
                childRules: [
                    'allowedTypes' => $internalLayoutChildren,
                ],
                integration: [
                    'rendererKey' => 'layout.container',
                    'editorKey' => 'layout.container',
                ],
            ),
            new ComponentDefinition(
                type: 'layout.stack',
                name: 'Stack',
                category: 'layout',
                description: 'A vertical flow layout with consistent spacing.',
                capabilities: ['canHaveChildren' => true, 'canAcceptChildren' => true, 'supportsResponsiveStyles' => true],
                defaultStyles: ['desktop' => ['display' => 'flex', 'flexDirection' => 'column', 'gap' => '16px']],
                styleCapabilities: ['display', 'width', 'minHeight', 'maxWidth', 'margin', 'padding', 'gap', 'flexDirection', 'justifyContent', 'alignItems', 'flexWrap', 'backgroundColor'],
                childRules: ['allowedTypes' => $internalLayoutChildren],
                integration: ['rendererKey' => 'layout.stack', 'icon' => 'stack'],
            ),
            new ComponentDefinition(
                type: 'layout.flex',
                name: 'Flex',
                category: 'layout',
                description: 'A flexible row or column layout primitive.',
                capabilities: ['canHaveChildren' => true, 'canAcceptChildren' => true, 'supportsResponsiveStyles' => true],
                defaultStyles: ['desktop' => ['display' => 'flex', 'flexDirection' => 'row', 'gap' => '16px']],
                styleCapabilities: ['display', 'width', 'minHeight', 'maxWidth', 'margin', 'padding', 'gap', 'flexDirection', 'justifyContent', 'alignItems', 'flexWrap', 'backgroundColor'],
                childRules: ['allowedTypes' => ['layout.column', ...$internalLayoutChildren]],
                integration: ['rendererKey' => 'layout.flex', 'icon' => 'flex'],
            ),
            new ComponentDefinition(
                type: 'layout.grid',
                name: 'Grid',
                category: 'layout',
                description: 'A responsive grid for cards and repeated content.',
                capabilities: ['canHaveChildren' => true, 'canAcceptChildren' => true, 'supportsResponsiveStyles' => true],
                defaultStyles: ['desktop' => ['display' => 'grid', 'gridTemplateColumns' => 'repeat(3, minmax(0, 1fr))', 'gap' => '16px']],
                styleCapabilities: ['display', 'width', 'minHeight', 'maxWidth', 'margin', 'padding', 'gap', 'gridTemplateColumns', 'backgroundColor'],
                childRules: ['allowedTypes' => $internalLayoutChildren],
                integration: ['rendererKey' => 'layout.grid', 'icon' => 'grid'],
            ),
            new ComponentDefinition(
                type: 'layout.columns',
                name: 'Columns',
                category: 'layout',
                description: 'A simple multi-column composition primitive.',
                capabilities: ['canHaveChildren' => true, 'canAcceptChildren' => true, 'supportsResponsiveStyles' => true],
                defaultStyles: ['desktop' => ['display' => 'flex', 'flexDirection' => 'row', 'gap' => '16px']],
                styleCapabilities: ['display', 'width', 'minHeight', 'maxWidth', 'margin', 'padding', 'gap', 'flexDirection', 'justifyContent', 'alignItems', 'flexWrap'],
                childRules: ['allowedTypes' => $internalLayoutChildren],
                integration: ['rendererKey' => 'layout.columns', 'icon' => 'columns'],
            ),
            new ComponentDefinition(
                type: 'layout.spacer',
                name: 'Spacer',
                category: 'layout',
                description: 'Adds intentional vertical space to a composition.',
                capabilities: ['supportsResponsiveStyles' => true],
                defaultStyles: ['desktop' => ['minHeight' => '32px']],
                styleCapabilities: ['width', 'height', 'minHeight', 'maxHeight', 'margin'],
                childRules: ['allowedTypes' => []],
                integration: ['rendererKey' => 'layout.spacer', 'icon' => 'spacer'],
            ),
            new ComponentDefinition(
                type: 'layout.divider',
                name: 'Divider',
                category: 'layout',
                description: 'A visual separator between content groups.',
                capabilities: ['supportsResponsiveStyles' => true],
                defaultStyles: ['desktop' => ['borderWidth' => '1px', 'borderStyle' => 'solid', 'borderColor' => 'hsl(160 10% 88%)']],
                styleCapabilities: ['width', 'margin', 'borderWidth', 'borderStyle', 'borderColor'],
                childRules: ['allowedTypes' => []],
                integration: ['rendererKey' => 'layout.divider', 'icon' => 'divider'],
            ),
            new ComponentDefinition(
                type: 'content.heading',
                name: 'Heading',
                category: 'content',
                description: 'Text heading content primitive.',
                capabilities: [
                    'supportsText' => true,
                    'supportsResponsiveStyles' => true,
                ],
                defaultProps: [
                    'text' => 'Heading',
                    'level' => 2,
                    'colorSegments' => [],
                ],
                defaultStyles: [
                    'desktop' => [
                        'fontSize' => '32px',
                    ],
                ],
                styleCapabilities: ['display', 'margin', 'padding', 'color', 'fontFamily', 'fontSize', 'fontWeight', 'lineHeight', 'textAlign'],
                propSchema: [
                    'text' => ['type' => 'string'],
                    'level' => ['type' => 'integer', 'min' => 1, 'max' => 6],
                    'colorSegments' => ['type' => 'array'],
                ],
                childRules: [
                    'allowedTypes' => [],
                ],
                integration: [
                    'rendererKey' => 'content.heading',
                    'editorKey' => 'content.heading',
                ],
            ),
            new ComponentDefinition(
                type: 'content.text',
                name: 'Text',
                category: 'content',
                description: 'A readable paragraph of body copy.',
                capabilities: ['supportsText' => true, 'supportsResponsiveStyles' => true],
                defaultProps: ['text' => 'Add a paragraph of text.', 'colorSegments' => []],
                defaultStyles: ['desktop' => ['fontSize' => '16px', 'lineHeight' => 1.6]],
                styleCapabilities: ['display', 'margin', 'padding', 'color', 'fontFamily', 'fontSize', 'fontWeight', 'lineHeight', 'letterSpacing', 'textTransform', 'textDecoration', 'textAlign'],
                propSchema: ['text' => ['type' => 'string'], 'colorSegments' => ['type' => 'array']],
                childRules: ['allowedTypes' => []],
                integration: ['rendererKey' => 'content.text', 'icon' => 'text'],
            ),
            new ComponentDefinition(
                type: 'content.richtext',
                name: 'Rich Text',
                category: 'content',
                description: 'Structured editorial copy for longer content.',
                capabilities: ['supportsText' => true, 'supportsResponsiveStyles' => true],
                defaultProps: ['text' => 'Add rich text content.', 'colorSegments' => []],
                styleCapabilities: ['display', 'margin', 'padding', 'color', 'fontFamily', 'fontSize', 'fontWeight', 'lineHeight', 'letterSpacing', 'textTransform', 'textDecoration', 'textAlign'],
                propSchema: ['text' => ['type' => 'string'], 'colorSegments' => ['type' => 'array']],
                childRules: ['allowedTypes' => []],
                integration: ['rendererKey' => 'content.richtext', 'icon' => 'rich-text'],
            ),
            new ComponentDefinition(
                type: 'content.button',
                name: 'Button',
                category: 'content',
                description: 'A clear action link for visitors.',
                capabilities: ['supportsText' => true, 'supportsResponsiveStyles' => true],
                defaultProps: ['text' => 'Get started', 'href' => '#'],
                defaultStyles: ['desktop' => ['display' => 'inline-block', 'padding' => '12px 16px', 'backgroundColor' => 'hsl(158 64% 32%)', 'color' => 'white', 'borderRadius' => '8px', 'textAlign' => 'center']],
                styleCapabilities: ['display', 'width', 'height', 'minWidth', 'maxWidth', 'minHeight', 'maxHeight', 'margin', 'padding', 'color', 'backgroundColor', 'fontFamily', 'fontSize', 'fontWeight', 'lineHeight', 'textAlign', 'borderRadius', 'borderWidth', 'borderStyle', 'borderColor', 'boxShadow'],
                propSchema: [
                    'text' => ['type' => 'string'],
                    'href' => ['type' => 'string'],
                    'icon' => ['type' => 'string'],
                    'customIcon' => ['type' => 'string'],
                    'iconPosition' => ['type' => 'enum', 'values' => ['left', 'right']],
                    'iconSpacing' => ['type' => 'string'],
                    'iconSize' => ['type' => 'string'],
                    'showIcon' => ['type' => 'boolean'],
                ],
                childRules: ['allowedTypes' => []],
                integration: ['rendererKey' => 'content.button', 'icon' => 'button'],
            ),
            new ComponentDefinition(
                type: 'content.link',
                name: 'Link',
                category: 'content',
                description: 'A lightweight inline navigation link.',
                capabilities: ['supportsText' => true, 'supportsResponsiveStyles' => true],
                defaultProps: ['text' => 'Learn more', 'href' => '#'],
                styleCapabilities: ['display', 'margin', 'padding', 'color', 'fontFamily', 'fontSize', 'fontWeight', 'lineHeight', 'textDecoration', 'textAlign'],
                propSchema: ['text' => ['type' => 'string'], 'href' => ['type' => 'string']],
                childRules: ['allowedTypes' => []],
                integration: ['rendererKey' => 'content.link', 'icon' => 'link'],
            ),
            new ComponentDefinition(
                type: 'media.image',
                name: 'Image',
                category: 'media',
                description: 'An image reference with accessible alt text.',
                capabilities: ['supportsResponsiveStyles' => true],
                defaultProps: ['src' => '', 'alt' => ''],
                styleCapabilities: ['display', 'width', 'height', 'minWidth', 'maxWidth', 'margin', 'borderRadius', 'objectFit'],
                propSchema: ['src' => ['type' => 'string'], 'alt' => ['type' => 'string']],
                childRules: ['allowedTypes' => []],
                integration: ['rendererKey' => 'media.image', 'icon' => 'image'],
            ),
            new ComponentDefinition(
                type: 'code.customcode',
                name: 'Custom Code',
                category: 'code',
                description: 'Raw HTML with style and script tags, rendered as-is.',
                capabilities: ['supportsText' => true],
                defaultProps: ['code' => "<style>\n  /* your styles */\n</style>\n<script>\n  // your script\n</script>\n"],
                propSchema: ['code' => ['type' => 'string']],
                childRules: ['allowedTypes' => []],
                integration: ['rendererKey' => 'code.customcode', 'icon' => 'code'],
            ),
            new ComponentDefinition(
                type: 'marketing.card',
                name: 'Card',
                category: 'marketing',
                description: 'A contained surface for grouped content.',
                capabilities: ['canHaveChildren' => true, 'canAcceptChildren' => true, 'supportsResponsiveStyles' => true],
                defaultStyles: ['desktop' => ['display' => 'flex', 'flexDirection' => 'column', 'gap' => '12px', 'padding' => '24px', 'backgroundColor' => 'white', 'borderWidth' => '1px', 'borderStyle' => 'solid', 'borderColor' => 'hsl(160 10% 88%)', 'borderRadius' => '12px', 'boxShadow' => '0 1px 2px rgba(0,0,0,.08)']],
                styleCapabilities: ['display', 'width', 'minHeight', 'maxWidth', 'margin', 'padding', 'gap', 'flexDirection', 'justifyContent', 'alignItems', 'backgroundColor', 'borderWidth', 'borderStyle', 'borderColor', 'borderRadius', 'borderTopLeftRadius', 'borderTopRightRadius', 'borderBottomRightRadius', 'borderBottomLeftRadius', 'boxShadow'],
                childRules: ['allowedTypes' => $internalLayoutChildren],
                integration: ['rendererKey' => 'marketing.card', 'icon' => 'card'],
            ),
            new ComponentDefinition(
                type: 'reusable.instance',
                name: 'Reusable component',
                category: 'content',
                description: 'A reference to an owned reusable component definition.',
                capabilities: ['supportsResponsiveStyles' => false],
                defaultProps: [],
                defaultStyles: [],
                styleCapabilities: [],
                propSchema: [],
                childRules: ['allowedTypes' => []],
                integration: ['rendererKey' => 'reusable.instance'],
            ),
            new ComponentDefinition(
                type: 'layout.navbar',
                name: 'Header & Menu',
                category: 'layout',
                description: 'Responsive website header with brand, navigation links, CTA button, and mobile hamburger toggle.',
                capabilities: ['canHaveChildren' => false, 'canAcceptChildren' => false, 'supportsResponsiveStyles' => true],
                defaultProps: [
                    'brandName' => 'HelloWeb',
                    'brandLogo' => '',
                    'brandHref' => '/',
                    'links' => [
                        ['label' => 'Home', 'href' => '/'],
                        ['label' => 'Features', 'href' => '#features'],
                        ['label' => 'Pricing', 'href' => '#pricing'],
                        ['label' => 'About', 'href' => '#about'],
                    ],
                    'ctaText' => 'Get Started',
                    'ctaHref' => '#',
                    'showCta' => true,
                    'sticky' => false,
                ],
                defaultStyles: [
                    'desktop' => [
                        'display' => 'block',
                        'width' => '100%',
                        'backgroundColor' => 'transparent',
                        'color' => 'inherit',
                        'paddingTop' => ['value' => 16, 'unit' => 'px'],
                        'paddingBottom' => ['value' => 16, 'unit' => 'px'],
                        'paddingLeft' => ['value' => 24, 'unit' => 'px'],
                        'paddingRight' => ['value' => 24, 'unit' => 'px'],
                        'borderBottomWidth' => ['value' => 0, 'unit' => 'px'],
                        'borderBottomStyle' => 'solid',
                        'borderBottomColor' => 'transparent',
                    ],
                ],
                styleCapabilities: [
                    'display', 'width', 'maxWidth', 'minHeight', 'height', 'margin', 'marginTop', 'marginRight', 'marginBottom', 'marginLeft',
                    'padding', 'paddingTop', 'paddingRight', 'paddingBottom', 'paddingLeft', 'backgroundColor', 'color',
                    'borderWidth', 'borderTopWidth', 'borderRightWidth', 'borderBottomWidth', 'borderLeftWidth',
                    'borderStyle', 'borderTopStyle', 'borderRightStyle', 'borderBottomStyle', 'borderLeftStyle',
                    'borderColor', 'borderTopColor', 'borderRightColor', 'borderBottomColor', 'borderLeftColor',
                    'borderRadius', 'borderTopLeftRadius', 'borderTopRightRadius', 'borderBottomRightRadius', 'borderBottomLeftRadius',
                    'boxShadow', 'dropShadowX', 'dropShadowY', 'dropShadowBlur', 'dropShadowSpread', 'dropShadowColor',
                    'innerShadowX', 'innerShadowY', 'innerShadowBlur', 'innerShadowSpread', 'innerShadowColor',
                    'layerBlur', 'backgroundBlur',
                    'glassRefraction', 'glassDepth', 'glassDispersion', 'glassFrost', 'glassSplay', 'glassLightDegree', 'glassOpacity',
                    'filter', 'backdropFilter', 'mixBlendMode', 'opacity',
                    'position', 'top', 'bottom', 'left', 'right', 'zIndex',
                    'fontFamily', 'fontSize', 'fontWeight', 'lineHeight', 'letterSpacing', 'textAlign',
                    'justifyContent', 'alignItems', 'gap', 'flexDirection',
                ],
                propSchema: [
                    'brandName' => ['type' => 'string', 'label' => 'Brand Name'],
                    'brandLogo' => ['type' => 'string', 'label' => 'Logo Image URL'],
                    'brandHref' => ['type' => 'string', 'label' => 'Brand URL'],
                    'links' => ['type' => 'array', 'label' => 'Navigation Links'],
                    'ctaText' => ['type' => 'string', 'label' => 'CTA Button Text'],
                    'ctaHref' => ['type' => 'string', 'label' => 'CTA URL'],
                    'showCta' => ['type' => 'boolean', 'label' => 'Show CTA Button'],
                    'sticky' => ['type' => 'boolean', 'label' => 'Sticky Header'],
                ],
                childRules: ['allowedTypes' => []],
                integration: ['rendererKey' => 'layout.navbar'],
            ),
            new ComponentDefinition(
                type: 'marketing.blurb',
                name: 'Feature Box',
                category: 'marketing',
                description: 'Feature box highlighting a key capability with icon, title, description, and link.',
                capabilities: ['canHaveChildren' => false, 'canAcceptChildren' => false, 'supportsResponsiveStyles' => true],
                defaultProps: [
                    'icon' => 'sparkles',
                    'title' => 'Modern & Intuitive',
                    'description' => 'Empower your workflow with intuitive tools engineered for speed and aesthetic perfection.',
                    'linkText' => 'Learn more →',
                    'linkHref' => '#',
                    'iconColor' => '#2563eb',
                    'iconBg' => '#eff6ff',
                ],
                defaultStyles: [
                    'desktop' => [
                        'display' => 'flex',
                        'flexDirection' => 'column',
                        'alignItems' => 'flex-start',
                        'padding' => '24px',
                        'backgroundColor' => '#ffffff',
                        'borderRadius' => '12px',
                        'borderWidth' => '1px',
                        'borderStyle' => 'solid',
                        'borderColor' => '#e2e8f0',
                        'gap' => '12px',
                    ],
                ],
                styleCapabilities: ['display', 'width', 'maxWidth', 'margin', 'padding', 'gap', 'flexDirection', 'alignItems', 'justifyContent', 'backgroundColor', 'borderWidth', 'borderStyle', 'borderColor', 'borderRadius', 'boxShadow', 'opacity'],
                propSchema: [
                    'icon' => ['type' => 'string', 'label' => 'Icon'],
                    'customIcon' => ['type' => 'string', 'label' => 'Custom Icon'],
                    'title' => ['type' => 'string', 'label' => 'Title'],
                    'description' => ['type' => 'string', 'label' => 'Description'],
                    'linkText' => ['type' => 'string', 'label' => 'Link Text'],
                    'linkHref' => ['type' => 'string', 'label' => 'Link Destination'],
                    'iconColor' => ['type' => 'string', 'label' => 'Icon Color'],
                    'iconBg' => ['type' => 'string', 'label' => 'Icon Background Color'],
                    'iconPosition' => ['type' => 'enum', 'label' => 'Icon Position', 'values' => ['top', 'left']],
                    'iconShape' => ['type' => 'enum', 'label' => 'Icon Shape', 'values' => ['rounded', 'circle', 'square', 'none']],
                ],
                childRules: ['allowedTypes' => []],
                integration: ['rendererKey' => 'marketing.blurb'],
            ),
            new ComponentDefinition(
                type: 'content.list',
                name: 'Styled List',
                category: 'content',
                description: 'Styled list with checkmarks, bullet points, or numbered badges.',
                capabilities: ['canHaveChildren' => false, 'canAcceptChildren' => false, 'supportsResponsiveStyles' => true],
                defaultProps: [
                    'listType' => 'check',
                    'icon' => 'check',
                    'items' => [
                        'Lightning-fast page loading',
                        'Fully responsive on mobile & tablet',
                        'SEO optimized clean markup',
                        'One-click instant publishing',
                    ],
                    'iconColor' => '#10b981',
                ],
                defaultStyles: [
                    'desktop' => [
                        'display' => 'flex',
                        'flexDirection' => 'column',
                        'gap' => '12px',
                        'width' => '100%',
                        'margin' => '0',
                        'padding' => '0',
                    ],
                ],
                styleCapabilities: ['display', 'width', 'maxWidth', 'margin', 'padding', 'gap', 'flexDirection', 'alignItems', 'justifyContent', 'opacity'],
                propSchema: [
                    'listType' => ['type' => 'enum', 'label' => 'List Style', 'values' => ['check', 'bullet', 'number', 'icon']],
                    'icon' => ['type' => 'string', 'label' => 'Icon'],
                    'customIcon' => ['type' => 'string', 'label' => 'Custom Icon'],
                    'iconColor' => ['type' => 'string', 'label' => 'Icon / Bullet Color'],
                    'iconSize' => ['type' => 'string', 'label' => 'Icon Size'],
                    'items' => ['type' => 'array', 'label' => 'Items'],
                    'text' => ['type' => 'string', 'label' => 'Items (One per line)'],
                ],
                childRules: ['allowedTypes' => []],
                integration: ['rendererKey' => 'content.list'],
            ),
            new ComponentDefinition(
                type: 'marketing.imagefeature',
                name: 'Image Feature',
                category: 'marketing',
                description: 'Split section pairing compelling copy and CTA with a prominent visual image.',
                capabilities: ['canHaveChildren' => false, 'canAcceptChildren' => false, 'supportsResponsiveStyles' => true],
                defaultProps: [
                    'badge' => 'FEATURE HIGHLIGHT',
                    'showBadge' => true,
                    'title' => 'Design at the speed of thought',
                    'showTitle' => true,
                    'description' => 'Create responsive, production-ready websites with a powerful visual editor built for modern teams.',
                    'showDescription' => true,
                    'imageSrc' => 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80',
                    'imageAlt' => 'Feature preview',
                    'imagePosition' => 'right',
                    'ctaText' => 'Explore Platform',
                    'ctaHref' => '#',
                    'showCta' => true,
                    'cardStyle' => true,
                    'buttonPosition' => 'bottom',
                ],
                defaultStyles: [
                    'desktop' => [
                        'display' => 'block',
                        'width' => '100%',
                        'backgroundColor' => '#ffffff',
                        'borderRadius' => '16px',
                        'borderWidth' => '1px',
                        'borderStyle' => 'solid',
                        'borderColor' => '#e2e8f0',
                        'padding' => '32px',
                        'boxShadow' => '0 1px 2px rgba(0,0,0,.08)',
                        'margin' => '0 auto',
                        'maxWidth' => '1140px',
                    ],
                ],
                styleCapabilities: ['display', 'width', 'maxWidth', 'margin', 'padding', 'backgroundColor', 'borderWidth', 'borderStyle', 'borderColor', 'borderRadius', 'boxShadow', 'opacity'],
                propSchema: [
                    'badge' => ['type' => 'string', 'label' => 'Badge'],
                    'showBadge' => ['type' => 'boolean', 'label' => 'Show Badge'],
                    'title' => ['type' => 'string', 'label' => 'Title'],
                    'showTitle' => ['type' => 'boolean', 'label' => 'Show Title'],
                    'description' => ['type' => 'string', 'label' => 'Description'],
                    'showDescription' => ['type' => 'boolean', 'label' => 'Show Description'],
                    'imageSrc' => ['type' => 'string', 'label' => 'Image URL'],
                    'imageAlt' => ['type' => 'string', 'label' => 'Image Alt'],
                    'imagePosition' => ['type' => 'enum', 'label' => 'Image Position', 'values' => ['left', 'right', 'top', 'bottom']],
                    'ctaText' => ['type' => 'string', 'label' => 'CTA Button Text'],
                    'ctaHref' => ['type' => 'string', 'label' => 'CTA URL'],
                    'showCta' => ['type' => 'boolean', 'label' => 'Show CTA Button'],
                    'cardStyle' => ['type' => 'boolean', 'label' => 'Display as Card'],
                    'buttonPosition' => ['type' => 'enum', 'label' => 'Button Position', 'values' => ['bottom', 'inline']],
                ],
                childRules: ['allowedTypes' => []],
                integration: ['rendererKey' => 'marketing.imagefeature'],
            ),
            new ComponentDefinition(
                type: 'media.gallery',
                name: 'Image Gallery',
                category: 'media',
                description: 'Responsive photo gallery with interactive full-screen lightbox preview.',
                capabilities: ['canHaveChildren' => false, 'canAcceptChildren' => false, 'supportsResponsiveStyles' => true],
                defaultProps: [
                    'columns' => 3,
                    'columnsDesktop' => 3,
                    'columnsTablet' => 2,
                    'columnsMobile' => 1,
                    'gap' => '16px',
                    'gapDesktop' => '16px',
                    'gapTablet' => '12px',
                    'gapMobile' => '8px',
                    'aspectRatio' => '4/3',
                    'images' => [
                        ['src' => 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80', 'caption' => 'Tropical Paradise'],
                        ['src' => 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=800&q=80', 'caption' => 'Misty Mountains'],
                        ['src' => 'https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?auto=format&fit=crop&w=800&q=80', 'caption' => 'Forest Canopy'],
                        ['src' => 'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?auto=format&fit=crop&w=800&q=80', 'caption' => 'Desert Dunes'],
                        ['src' => 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=800&q=80', 'caption' => 'Wilderness Vista'],
                        ['src' => 'https://images.unsplash.com/photo-1433086966358-54859d0ed716?auto=format&fit=crop&w=800&q=80', 'caption' => 'Cascading Falls'],
                    ],
                ],
                defaultStyles: [
                    'desktop' => [
                        'display' => 'block',
                        'width' => '100%',
                        'margin' => '0 auto',
                        'padding' => '16px 0',
                        'maxWidth' => '1140px',
                    ],
                ],
                styleCapabilities: ['display', 'width', 'maxWidth', 'margin', 'padding', 'opacity'],
                propSchema: [
                    'columns' => ['type' => 'integer', 'label' => 'Columns'],
                    'columnsDesktop' => ['type' => 'integer', 'label' => 'Desktop Columns'],
                    'columnsTablet' => ['type' => 'integer', 'label' => 'Tablet Columns'],
                    'columnsMobile' => ['type' => 'integer', 'label' => 'Mobile Columns'],
                    'gap' => ['type' => 'string', 'label' => 'Grid Gap'],
                    'gapDesktop' => ['type' => 'string', 'label' => 'Desktop Gap'],
                    'gapTablet' => ['type' => 'string', 'label' => 'Tablet Gap'],
                    'gapMobile' => ['type' => 'string', 'label' => 'Mobile Gap'],
                    'aspectRatio' => ['type' => 'string', 'label' => 'Aspect Ratio'],
                    'images' => ['type' => 'array', 'label' => 'Gallery Images'],
                ],
                childRules: ['allowedTypes' => []],
                integration: ['rendererKey' => 'media.gallery'],
            ),
        ];
    }

    public static function registry(): ComponentRegistry
    {
        return new ComponentRegistry(self::all());
    }
}
