<?php

namespace App\Builder\Style;

final class StyleSchema
{
    /** @return array<string, StyleDefinition> */
    public static function definitions(): array
    {
        $length = static fn (string $key, string $label, string $group): StyleDefinition => new StyleDefinition($key, $label, $group, 'length');
        $enum = static fn (string $key, string $label, string $group, array $options): StyleDefinition => new StyleDefinition($key, $label, $group, 'enum', options: $options);
        $definitions = [
            $enum('display', 'Display', 'layout', ['block', 'inline', 'inline-block', 'flex', 'grid', 'none']), $length('width', 'Width', 'layout'), $length('height', 'Height', 'layout'),
            $length('minWidth', 'Minimum width', 'layout'), $length('maxWidth', 'Maximum width', 'layout'), $length('minHeight', 'Minimum height', 'layout'), $length('maxHeight', 'Maximum height', 'layout'),
            $length('margin', 'Margin', 'layout'), $length('marginTop', 'Margin top', 'layout'), $length('marginRight', 'Margin right', 'layout'), $length('marginBottom', 'Margin bottom', 'layout'), $length('marginLeft', 'Margin left', 'layout'), $length('padding', 'Padding', 'layout'), $length('paddingTop', 'Padding top', 'layout'), $length('paddingRight', 'Padding right', 'layout'), $length('paddingBottom', 'Padding bottom', 'layout'), $length('paddingLeft', 'Padding left', 'layout'), $length('gap', 'Gap', 'layout'), $enum('overflow', 'Overflow', 'layout', ['visible', 'hidden', 'auto', 'scroll']), $enum('gridTemplateColumns', 'Grid columns', 'layout', ['1fr', 'repeat(2, minmax(0, 1fr))', 'repeat(3, minmax(0, 1fr))', 'repeat(4, minmax(0, 1fr))']),
            $enum('flexDirection', 'Direction', 'flex', ['row', 'row-reverse', 'column', 'column-reverse']), $enum('justifyContent', 'Justify', 'flex', ['flex-start', 'flex-end', 'center', 'space-between', 'space-around', 'space-evenly']), $enum('alignItems', 'Align', 'flex', ['stretch', 'flex-start', 'flex-end', 'center', 'baseline']), $enum('flexWrap', 'Wrap', 'flex', ['nowrap', 'wrap', 'wrap-reverse']),
            $enum('position', 'Position', 'position', ['static', 'relative', 'absolute', 'fixed', 'sticky']), $length('top', 'Top', 'position'), $length('right', 'Right', 'position'), $length('bottom', 'Bottom', 'position'), $length('left', 'Left', 'position'), new StyleDefinition('zIndex', 'Z index', 'position', 'number'),
            new StyleDefinition('backgroundColor', 'Background color', 'background', 'color'), $enum('backgroundType', 'Background type', 'background', ['solid', 'gradient', 'image', 'video']), new StyleDefinition('backgroundGradient', 'Gradient', 'background', 'string'), new StyleDefinition('backgroundImage', 'Background image', 'background', 'string'), new StyleDefinition('backgroundVideo', 'Background video', 'background', 'string'), $enum('backgroundSize', 'Background size', 'background', ['cover', 'contain', 'auto', '100% 100%']), new StyleDefinition('backgroundPosition', 'Background position', 'background', 'string'), $enum('backgroundRepeat', 'Background repeat', 'background', ['no-repeat', 'repeat', 'repeat-x', 'repeat-y', 'space', 'round']), $enum('backgroundAttachment', 'Background attachment', 'background', ['scroll', 'fixed', 'local']), $enum('backgroundOrigin', 'Background origin', 'background', ['border-box', 'padding-box', 'content-box']), $enum('backgroundClip', 'Background clip', 'background', ['border-box', 'padding-box', 'content-box', 'text']), $enum('backgroundBlendMode', 'Blend mode', 'background', ['normal', 'multiply', 'screen', 'overlay', 'darken', 'lighten', 'color-dodge', 'color-burn', 'hard-light', 'soft-light', 'difference', 'exclusion', 'hue', 'saturation', 'color', 'luminosity']), $length('borderWidth', 'Border width', 'border'), $length('borderTopWidth', 'Top border width', 'border'), $length('borderRightWidth', 'Right border width', 'border'), $length('borderBottomWidth', 'Bottom border width', 'border'), $length('borderLeftWidth', 'Left border width', 'border'), $enum('borderStyle', 'Border style', 'border', ['none', 'solid', 'dashed', 'dotted', 'double']), new StyleDefinition('borderColor', 'Border color', 'border', 'color'), $length('borderRadius', 'Border radius', 'border'), $length('borderTopLeftRadius', 'Top left radius', 'border'), $length('borderTopRightRadius', 'Top right radius', 'border'), $length('borderBottomRightRadius', 'Bottom right radius', 'border'), $length('borderBottomLeftRadius', 'Bottom left radius', 'border'), $enum('objectFit', 'Object fit', 'layout', ['contain', 'cover', 'fill', 'none']),
            new StyleDefinition('color', 'Color', 'text', 'color'), $enum('fontFamily', 'Font family', 'text', ['Inter', 'Manrope', 'DM Sans', 'Plus Jakarta Sans', 'Outfit', 'Poppins', 'Roboto', 'Open Sans', 'Montserrat', 'Lato', 'Nunito', 'Nunito Sans', 'Raleway', 'Oswald', 'Rubik', 'Work Sans', 'Figtree', 'Urbanist', 'Space Grotesk', 'Sora', 'Source Sans 3', 'IBM Plex Sans', 'Merriweather', 'Playfair Display', 'Libre Baskerville', 'Cormorant Garamond', 'Roboto Slab', 'IBM Plex Mono', 'JetBrains Mono', 'Fira Code', 'Source Code Pro', 'Arial', 'Helvetica', 'Helvetica Neue', 'Verdana', 'Tahoma', 'Trebuchet MS', 'Georgia', 'Times New Roman', 'Courier New', 'system-ui', 'sans-serif', 'serif', 'monospace']), $length('fontSize', 'Font size', 'text'), new StyleDefinition('fontWeight', 'Font weight', 'text', 'number'), new StyleDefinition('lineHeight', 'Line height', 'text', 'number'), $enum('textAlign', 'Text align', 'text', ['left', 'center', 'right', 'justify']), $length('letterSpacing', 'Letter spacing', 'text'), $enum('textTransform', 'Text transform', 'text', ['none', 'uppercase', 'lowercase', 'capitalize']), $enum('textDecoration', 'Text decoration', 'text', ['none', 'underline', 'line-through']), new StyleDefinition('boxShadow', 'Shadow', 'effects', 'enum', options: ['none', '0 1px 2px rgba(0,0,0,.08)', '0 8px 24px rgba(0,0,0,.12)', '0 18px 50px rgba(15,23,42,.18)', '0 24px 80px rgba(15,23,42,.28)', 'inset 0 1px 0 rgba(255,255,255,.35), 0 18px 50px rgba(15,23,42,.18)']), new StyleDefinition('opacity', 'Opacity', 'effects', 'number'), new StyleDefinition('filter', 'Filter', 'effects', 'string'), new StyleDefinition('backdropFilter', 'Backdrop filter', 'effects', 'string'), $enum('mixBlendMode', 'Blend', 'effects', ['normal', 'multiply', 'screen', 'overlay', 'darken', 'lighten', 'difference', 'exclusion', 'color', 'luminosity']),
            new StyleDefinition('dropShadowX', 'Drop shadow X', 'effects', 'number'), new StyleDefinition('dropShadowY', 'Drop shadow Y', 'effects', 'number'), new StyleDefinition('dropShadowBlur', 'Drop shadow blur', 'effects', 'number'), new StyleDefinition('dropShadowSpread', 'Drop shadow spread', 'effects', 'number'), new StyleDefinition('dropShadowColor', 'Drop shadow color', 'effects', 'color'),
            new StyleDefinition('innerShadowX', 'Inner shadow X', 'effects', 'number'), new StyleDefinition('innerShadowY', 'Inner shadow Y', 'effects', 'number'), new StyleDefinition('innerShadowBlur', 'Inner shadow blur', 'effects', 'number'), new StyleDefinition('innerShadowSpread', 'Inner shadow spread', 'effects', 'number'), new StyleDefinition('innerShadowColor', 'Inner shadow color', 'effects', 'color'),
            new StyleDefinition('layerBlur', 'Layer blur', 'effects', 'number'), new StyleDefinition('backgroundBlur', 'Background blur', 'effects', 'number'),
            new StyleDefinition('glassRefraction', 'Refraction', 'effects', 'number'), new StyleDefinition('glassDepth', 'Depth', 'effects', 'number'), new StyleDefinition('glassDispersion', 'Dispersion', 'effects', 'number'), new StyleDefinition('glassFrost', 'Frost', 'effects', 'number'), new StyleDefinition('glassSplay', 'Splay', 'effects', 'number'), new StyleDefinition('glassLightDegree', 'Light degree', 'effects', 'number'), new StyleDefinition('glassOpacity', 'Glass opacity', 'effects', 'number'),
        ];
        $result = [];
        foreach ($definitions as $definition) {
            $result[$definition->key] = $definition;
        }

        return $result;
    }
}
