<?php

return [
    'default_provider' => env('AI_PROVIDER', 'openai'),
    'providers' => [
        'openai' => [
            'label' => 'OpenAI',
            'env_key' => 'OPENAI_API_KEY',
            'env_model' => 'OPENAI_MODEL',
            'default_model' => env('OPENAI_MODEL', 'gpt-4.1-mini'),
            'key_placeholder' => 'sk-...',
            'models' => ['gpt-4.1-mini', 'gpt-4.1', 'gpt-4o-mini', 'gpt-4o'],
            'test_url' => 'https://api.openai.com/v1/models',
            'auth' => 'bearer',
        ],
        'anthropic' => [
            'label' => 'Anthropic',
            'env_key' => 'ANTHROPIC_API_KEY',
            'env_model' => 'ANTHROPIC_MODEL',
            'default_model' => env('ANTHROPIC_MODEL', 'claude-3-5-sonnet-latest'),
            'key_placeholder' => 'sk-ant-...',
            'models' => ['claude-3-5-sonnet-latest', 'claude-3-5-haiku-latest', 'claude-3-opus-latest'],
            'test_url' => 'https://api.anthropic.com/v1/models',
            'auth' => 'anthropic',
        ],
        'google' => [
            'label' => 'Google Gemini',
            'env_key' => 'GEMINI_API_KEY',
            'env_model' => 'GEMINI_MODEL',
            'default_model' => env('GEMINI_MODEL', 'gemini-1.5-pro'),
            'key_placeholder' => 'AIza...',
            'models' => ['gemini-1.5-pro', 'gemini-1.5-flash', 'gemini-2.0-flash'],
            'test_url' => 'https://generativelanguage.googleapis.com/v1beta/models',
            'auth' => 'query_key',
        ],
        'openrouter' => [
            'label' => 'OpenRouter',
            'env_key' => 'OPENROUTER_API_KEY',
            'env_model' => 'OPENROUTER_MODEL',
            'default_model' => env('OPENROUTER_MODEL', 'openai/gpt-4o-mini'),
            'key_placeholder' => 'sk-or-...',
            'models' => ['openai/gpt-4o-mini', 'openai/gpt-4o', 'anthropic/claude-3.5-sonnet', 'google/gemini-pro-1.5'],
            'test_url' => 'https://openrouter.ai/api/v1/models',
            'auth' => 'bearer',
        ],
        'groq' => [
            'label' => 'Groq',
            'env_key' => 'GROQ_API_KEY',
            'env_model' => 'GROQ_MODEL',
            'default_model' => env('GROQ_MODEL', 'llama-3.1-70b-versatile'),
            'key_placeholder' => 'gsk_...',
            'models' => ['llama-3.1-70b-versatile', 'llama-3.1-8b-instant', 'mixtral-8x7b-32768'],
            'test_url' => 'https://api.groq.com/openai/v1/models',
            'auth' => 'bearer',
        ],
        'xai' => [
            'label' => 'xAI',
            'env_key' => 'XAI_API_KEY',
            'env_model' => 'XAI_MODEL',
            'default_model' => env('XAI_MODEL', 'grok-2-latest'),
            'key_placeholder' => 'xai-...',
            'models' => ['grok-2-latest', 'grok-2-mini-latest'],
            'test_url' => 'https://api.x.ai/v1/models',
            'auth' => 'bearer',
        ],
    ],
];
